### ISSUE TITLE
Two commands to launch Sensors in the Command Menu

### ISSUE THREAD

**Issue by pankajparashar** [MicrosoftEdge/DevTools#101]
I'm wondering why there are two options to open the **Sensors** drawer? Both the options seem to be doing the same thing.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/38640616/190850114-b1a69331-be95-40fc-933e-cd6719cf8a89.png">

AB#41385461

**Comment by captainbrosset** [comment]
Thanks for filing. I'll make sure this shows up on the team's radar. It seems to me like we should just remove one in this case.

**Comment by pankajparashar** [comment]
It's the same issue in Chrome as well, so I guess it could be an upstream issue.

**Comment by captainbrosset** [comment]
I reported it here too: https://bugs.chromium.org/p/chromium/issues/detail?id=1365975
