### ISSUE TITLE
JavaScript Tooltip disappear in Console

### ISSUE THREAD

**Issue by wuuconix** [MicrosoftEdge/DevTools#102]
Previously, edge DevTools Console show the javascript expression autocompletion in a block menu (I call it tooltip here).

you can find the tooltip what looks like [here](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/console-javascript#autocompletion-to-write-complex-expressions) in microsoft docs

![image](https://user-images.githubusercontent.com/80732538/190889413-04255749-6316-4aa6-a11a-33cbf5116600.png)

I think the tooltip is good, but now it is gone. I try to configure in the devtool settings, but failed.

![image](https://user-images.githubusercontent.com/80732538/190889294-131749ba-95b2-4371-9ac0-c9bdfbe11b81.png)

I check it in my classmate's edge console, no tooltip too.

Is there some way to make tooltip back again?

my edge version is 105.0.1343.42

AB#41385493

**Comment by captainbrosset** [comment]
Thanks so much for reporting this. I see the tooltip is working correctly in 106. So, this bug is limited to 105. I'll make sure the DevTools team sees this on their radar so they can evaluate the options for fixing it in 105.

**Comment by xqm32** [comment]
same😟

**Comment by captainbrosset** [comment]
Thanks for confirming. We are currently investigating this and will report back.

**Comment by NicoKam** [comment]
Is there a way to fix this bug temporary? 
Like registry or cli-arguments?

**Comment by captainbrosset** [comment]
I don't believe there is a way to fix this, other than to wait for the next version of Edge to roll out (which should be in 8 or 9 days from today). You can also download the Beta channel of Edge to get 106 earlier: https://www.microsoftedgeinsider.com/en-us/download/beta
