### ISSUE TITLE
Copy feature for Computed styles

### ISSUE THREAD

**Issue by pankajparashar** [MicrosoftEdge/DevTools#104]
**Problem statement:**
Currently it is not possible to copy the computed style values from the Computed pane. User can neither select the text nor use `Cmd/Ctrl+C` to copy the value. The only option is to click a tiny arrow icon to jump to the source, which if is a CSS variable, then click on the link to jump to its initialised value. This can go on if nested variables are used (see GIF below).

**Illustration of Frustration:**
It takes 3+ clicks to get the color value which could be just 1 click if there was a copy option,
![ScreenFlow](https://user-images.githubusercontent.com/38640616/191488455-489232d0-465e-46f8-9bff-dd97a584a842.gif)

**Proposal:**
Allow the user to select the text (`user-select:text`?) and then copy by traditional means or add a copy option in the right-click menu. Some other ideas were to add an option in the right click menu of the DOM element, `Copy` > `Copy Computed Styles`, which isn't practical to copy just one property value.

AB#41445912

**Comment by captainbrosset** [comment]
Cool feature request. Personally, I like the right-click > copy property proposal because there's a similar thing in the Styles panel too. But being able to just select and copy text seems like something that should never have been disabled. But maybe there's a reason for this that I'm not aware of.

I'll add this to our team's backlog for evaluation and prioritization.

**Comment by yisibl** [comment]
I have a prototype for copying the calculated values of CSS variables, which can be followed here: https://bugs.chromium.org/p/chromium/issues/detail?id=1380779

![image](https://user-images.githubusercontent.com/2784308/200036028-10107dec-53dc-40c4-ab5d-e0fb24e1eb8e.png)

For the issue of not being able to right-click to copy, I can go fix it.

**Comment by captainbrosset** [comment]
Tested today, I was able to select the text in the Computed pane by dragging my mouse, and then copy it with Ctrl+C.
So this has been resolved upstream.
