### ISSUE TITLE
Microsoft Edge dev tools search function takes a long time indexing

### ISSUE THREAD

**Issue by rod-wilson** [MicrosoftEdge/DevTools#105]
Hi folks,

I am using Microsoft Edge Version 104.0.1293.63 (Official build) (64-bit) and I have noticed that when I use the search function in the dev tools it now takes a very long time indexing before it returns its results. 

Now I am pretty sure this did not happen before and the same function in Google Chrome dev tools is almost instant.

I have tried using the "restore defaults and refresh" option in the dev tools config to see if it was due to a config setting I have switched on inadvertently, but it is still the same so I can only think it could be due to the version of Edge I now have.
![MS-Edge-Dev-Tools-Search-Indexing](https://user-images.githubusercontent.com/114173093/191795226-e60fbd8e-f648-4e13-9c34-0b13e616e2fc.png)

Attached is a screenshot, it always happens not just occasionally - but I have no idea what governs this indexing aspect in dev tools.

Regards

Rod

AB#41510476

**Comment by captainbrosset** [comment]
Thank you Rod for reaching out about this.

Does this only happen on the same webpage, or on any webpage you inspect?
If it happens a particular webpage, then please share the URL so we can investigate and fix the problem.

Can you say more precisely how much time it takes? Oh, and does this happen irrespective of the string you type in the search field?

**Comment by rod-wilson** [comment]
It happens on every web page and for every search term. It can take 2-3 minutes to complete this indexing process and then the search results are returned.

**Comment by rod-wilson** [comment]
Hi, just an update, 

I received a new laptop with Microsoft Edge Build 106.0.1370.42 and I do not see the issue anymore.

Regards, Rod
