### ISSUE TITLE
Edge 105 and 106 send cipher 4866 twice in ClientHello

### ISSUE THREAD

**Issue by michaelgranzow-avi** [MicrosoftEdge/DevTools#110]
The Cipher Suite 
```
TLS_AES_256_GCM_SHA384 (0x1302)
```
is sent twice in ClientHellos by Edge in versions 105 and 106: once in position 2 and again in position 3 of the cipher list.

It makes no sense to send the same cipher twice, and some very defensive TLS stacks reject such ClientHellos.

I haven't seen this behaviour from Chrome or the other Chromium-derived browsers.

**Comment by captainbrosset** [comment]
Thanks for reporting this. However, this isn't related to Edge DevTools, but rather to the browser itself. The right channel to send feedback about the browser is in the browser directly:

* Click **Settings and more** (the `...` button in the toolbar).
* **Help and feedback**.
* **Send feedback**.

Can you please send your message again this way? Thanks for your understanding!
