### ISSUE TITLE
"scroll-behavior is not supported by Safari ..."-warning displayed on ALL style properties

### ISSUE THREAD

**Issue by Svish** [MicrosoftEdge/DevTools#113]
Being warned in the Edge DevTools that "scroll-behavior is not supported by Safari ..." is useful, but not when you put that warning on _every single CSS property everywhere_.

It creates _a lot_ of noise, looks terrible, and makes it _impossible_ to know if there are any _other_ warnings I should know about. And I'm not kidding, it's _everywhere_, _every_ single style property shown, regardless of what element I have selected.

![image](https://user-images.githubusercontent.com/142162/199722673-2018f821-00c4-4f1f-a15b-4ad293994860.png)

---
As requested by https://twitter.com/patrickbrosset/status/1588111219285757952

AB#42085000

**Comment by captainbrosset** [comment]
Thanks so much for filing this issue @Svish. This definitely seems like a bug, and we should investigate. I'll make sure this is tracked by the team, and let's keep this issue opened for any questions or updates.

**Comment by captainbrosset** [comment]
@Svish here are a few questions to get us started, the more you can answer, the better!

* Does this happen in DevTools within the browser, or when using our VS Code extension?
* Does this happen on all webpages, or only on some (if so, which ones)?
* Does this happen on all elements, or just some?
* Do you even use the `scroll-behavior` CSS property in your code?

**Comment by Svish** [comment]
@captainbrosset 

* It happens in the browser, `Version 107.0.1418.26 (Official build) (64-bit)`  
(... there's an Edge/DevTools VS Code extension?)
* It seems to happen on all webpages of our website at least. Example:  
https://www.opf.no/om-oss/om-opf/
* All elements, and all style properties on every element
* Yes, `scroll-behavior: smooth` is defined on the `html` element, but nowhere else (as far as I know)

Testing it again I actually noticed there's an error as well (which also ends up on _all_ style properties _everywhere_), "-moz-appearance is not supported by Chrome, ... ". But then soon after it gets overridden(?) by the "scroll-behavoir"-warning. 🤷‍♂️

Made a GIF:

![GIF 03 11 2022 15-06-32](https://user-images.githubusercontent.com/142162/199742901-13cde3c0-c13f-4d86-9f26-3fdde6ba87e5.gif)

**Comment by vidorteg** [comment]
Thank you for reporting this @Svish , this should be fixed in Dev and Canary version of Microsoft Edge  (`109.0.1495.2 (Official build) dev (64-bit)` and more recent ) could you please give a try there and see if it stills reproes? If using the Dev channel is not an option you can also temporarily turn off this experiment under:
- Developer Tools `Settings` -> Experiments -> `Show issues in Elements`

If none of the previous options works please reopen the issue so that we can take another look. Thanks again for helping to make Developer Tools better.
