### ISSUE TITLE
Issue opening DevTools when using allow and block list in Edge

### ISSUE THREAD

**Issue by neckermann** [MicrosoftEdge/DevTools#118]
We have our Edge browser locked down to just a few sites. With the sites in the allow list and a block list of *.

When this is in place, we are unable to open the Edge Dev tools. 

Can you share the url handler we need to add to the allow list for this to work. 
If we move our block list to just http://* or https://* dev tools open so I assume it is something like
devtools://*

**Comment by captainbrosset** [comment]
Thanks for reaching out about this. Let me try to find this information for you and get back to you as soon as I can.

**Comment by neckermann** [comment]
@captainbrosset any luck finding the url handler?

**Comment by captainbrosset** [comment]
Not yet unfortunately, but I'll make sure to update this thread as soon as I do.

**Comment by captainbrosset** [comment]
@neckermann you can probably start with adding `devtools://devtools/*` to the allow-list. You might also need to add `https://devtools.azureedge.net/*` to the allow-list. 

I'm not sure if this will work, but it's worth trying out. Let me know!

**Comment by captainbrosset** [comment]
Something else worth trying is changing the DeveloperToolsAvailability policy ([docs](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#developertoolsavailability)). Your environment may be configured to not have DevTools available.

In fact, we ran into this with WebDriver here and documented the work around here: [Use WebDriver to automate Microsoft Edge](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp#developer-tools-availability-policy).

**Comment by neckermann** [comment]
@captainbrosset 
So it looks like devtools://* worked for us.

Thanks
