### ISSUE TITLE
Network Console: Unable to send a POST/PUT request with JSON content

### ISSUE THREAD

**Issue by mikegoatly** [MicrosoftEdge/DevTools#120]
Edge version: 108.0.1462.42 (Official build) (64-bit)

When I go to the Network Console to send a request with JSON content, selecting the Raw text options just ends up with a "Loading..." placeholder and I can't edit the request to send:

<img width="383" alt="Screenshot 2022-12-07 093936" src="https://user-images.githubusercontent.com/4577868/206144307-9b79e666-667d-4206-9867-4b6ee2afcaf1.png">

I've tried restarting the browser, but the problem persists.

AB#42556577

**Comment by captainbrosset** [comment]
Thanks so much for reporting this. It definitely seems like a regression, and I'll make sure this goes on to the team's radar for the next bug fixing sprint.

**Comment by captainbrosset** [comment]
I'm told we have a fix almost ready! We'll update this thread when it's out, and will specify the version of Edge that has it.

**Comment by rafalfitt** [comment]
https://twitter.com/robpaveza/status/1601245091242266625
I can confirm, now it is working for me.

**Comment by captainbrosset** [comment]
Great! Closing the issue now.

**Comment by hj8e45** [comment]
#228 problem again
