### ISSUE TITLE
Long composite layers task when advanced instrumentation turned on

### ISSUE THREAD

**Issue by rebornix** [MicrosoftEdge/DevTools#123]
I was following https://blogs.windows.com/msedgedev/2023/01/17/the-truth-about-css-selector-performance/ and experiment with selector stats on github.dev. Interesting, while running performance profiler, if we only have file explorer open, the UI is snappy but as long as we have editors open, UI freezes frequently. From the perf log it seems multiple long "composite layers" tasks occur.

<img width="534" alt="image" src="https://user-images.githubusercontent.com/876920/213255760-5b183943-16a2-4299-9743-fdcf5f6502fe.png">

**Comment by captainbrosset** [comment]
Thanks for reaching out. It seems like it would be better to move this issue to the VSCode repository, right? Am I understanding correctly that this is meant as a performance feedback about VSCode, rather than feedback about the DevTools performance profiler?

**Comment by leahmsft** [comment]
Needs more information, closing for now
