### ISSUE TITLE
Request for Chrome Extension Support and Ad Blocker Recommendation

### ISSUE THREAD

**Issue by skul9x** [MicrosoftEdge/DevTools#129]
Dear Microsoft Edge Developers,

I hope this email finds you well. I am a loyal user of the Microsoft Edge browser on both desktop and mobile devices and I appreciate the effort you put into constantly improving the user experience.

I am writing to bring to your attention my desire to use Chrome extensions on the Edge mobile browser. As a user, I find it extremely convenient to have access to my favorite extensions on all my devices, and I believe this feature would greatly enhance the overall user experience on Edge mobile.

In addition, I would like to recommend the use of uBlock Origin as the preferred ad blocker on Edge mobile. While Adblock Plus is a great ad blocker, uBlock Origin is a more efficient and lightweight solution, which I believe would greatly improve the performance of the Edge mobile browser.

I appreciate your consideration and look forward to any updates regarding the integration of Chrome extensions and the recommendation of uBlock Origin as the preferred ad blocker on Edge mobile.

Thank you!

**Comment by captainbrosset** [comment]
Thank you for reaching out. However this repository is specifically focused on DevTools (the web development tools that are embedded inside of Microsoft Edge). This repo isn't a place to provide feedback about the browser itself.

Here are two ways to send your feedback to the Edge development team:

* In the Edge browser, on desktop, press `Alt+Shift+I` to open the feedback window.
* Or, join the edgeinsiders forum to discuss with the community: https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider

Hope this useful.
