### ISSUE TITLE
Restore split window upon start

### ISSUE THREAD

**Issue by AndreHorst** [MicrosoftEdge/DevTools#132]
I recently tested the split window feature and it is great. However, when Edge is set to restore tabs from previous session, and this session includes tabs that have split windows, the split window is not restored, but the two windows are restored as individual new tabs. Is this intended or a bug?

![image](https://user-images.githubusercontent.com/25814609/218277065-e58b4be0-af0a-4517-8d7c-7b0a0486160c.png)

Before closing Edge:
![image](https://user-images.githubusercontent.com/25814609/218277143-e37f37d1-d15d-489e-954a-3daf827b3a1c.png)

After closing and re-starting Edge:
![image](https://user-images.githubusercontent.com/25814609/218277238-74ba4cea-fc0b-40b7-b43f-fbd7897d326f.png)

**Comment by captainbrosset** [comment]
Thank you for reaching out, however this repository is specifically about the developer tools that are embedded inside of Edge. Not about Edge itself.
Could you please send your message again through the browser feedback channel? In Edge, press `Alt`+`Shift`+`I` to open the feedback dialog and enter your message!
Thanks a lot for your understanding.
