### ISSUE TITLE
SAP Business Objects 4.2 Webi not working

### ISSUE THREAD

**Issue by ccaldwellspinsup** [MicrosoftEdge/DevTools#133]
What steps will reproduce the problem?
(1) Open SAP Business Objects open any report and select refresh

What is the expected result?
Reports return result daya sets.

What happens instead?
Report just sit and spin and never complete.

Please provide any additional information below. Attach a screenshot if
possible.

In Chrome Release 109.0.5414 this was not and issue. If we revert to this version the reports work as expected. when updated to the 110 release reports cease to return. 

This only occurs in Chrome, does not happen in Edge, or firefox

For graphics-related bugs, please save the contents of the about:gpu page
to a text file and attach it to this bug report as an attachment.

Please see chromium bug page for more. This is affecting edge versions as well. 

https://bugs.chromium.org/p/chromium/issues/detail?id=1414463

**Comment by captainbrosset** [comment]
Thanks for reaching out, unfortunately this does not seem related to Edge or DevTools, so I'll have to close this issue now.
This repository is specifically about the developer tools in Edge (F12).
