### ISSUE TITLE
Tabs cant unmute.

### ISSUE THREAD

**Issue by hpss2000** [MicrosoftEdge/DevTools#137]
Even when i press ctrl+m or fn it visually unmutes but doesnt give any sound.this problem happens only with edge browser.i have used in different browsers and play youtube videos through my earbuds flawlessly .i have uninstalled and installed again at no change.can anybody help me?i use an hp all in one 2020 27 inch.
Many thanks in advance!

**Comment by captainbrosset** [comment]
I'm sorry you're having this problem. Unfortunately, here isn't the right place to report it. Would you please be so kind and report your issue using Edge's feedback tool? Here's how:

1. Click the `...` icon in the top right corner of Edge.
2. Select `Help and feedback`.
3. Click `Send feedback`.

A window will appear where you can report your issue and provide more details, including screenshots and system details.
