### ISSUE TITLE
More graphical representations of the heap snapshot

### ISSUE THREAD

**Issue by zoherghadyali** [MicrosoftEdge/DevTools#14]
**Value**: Developers can understand the relations between nodes and edges.

**Precedent**: 
- Firefox currently has a view for this inside Memory panel. 
- There are open source projects from web devs that parse heap snapshots from DevTools and show force directed graphs.

**Potential problems**: Visualizations like this may be hard to navigate as the number of nodes increase.

**Prototype / Mocks**
![heap-snapshot-graph](https://user-images.githubusercontent.com/34316555/157143482-a27fa82f-fa73-4e0b-acd5-0dc0ce067b1b.png)

A modified version of one of the open source projects, showing a simple heap snapshot. 

![heap-snapshot-tree-map](https://user-images.githubusercontent.com/34316555/157143504-9f9ea0cb-7dcd-4645-b99f-5e0cd3ff5560.gif)

**Comment by captainbrosset** [comment]
Just to illustrate what you said about Firefox, here is what it has:

<img width="1126" alt="screenshot of the Firefox Memory tool, showing the Tree Map view" src="https://user-images.githubusercontent.com/1152698/157671107-aa4bc163-7831-4d97-a85c-5c7ef5f479c2.png">

**Comment by captainbrosset** [comment]
I think it might be wise to dupe this to #36 since that other issue has got a prototype already, and a bunch of positive reactions.

Duplicate of #36.

**Comment by Fasteroid** [comment]
> A modified version of one of the open source projects, showing a simple heap snapshot.

@zoherghadyali which one?  I'd really really like to use this!
