### ISSUE TITLE
State of DevTools panel is not maintained on Focus Mode UI

### ISSUE THREAD

**Issue by mondaychen** [MicrosoftEdge/DevTools#140]
I noticed in Focus Mode, the state of a panel is not maintained when users switch to another panel and switch back.
This issue does not exist when Focus Mode is off

### Repro steps

1. Install React Developer Tools https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil
2. Go to a page running React, e.g. https://react.dev/
3. Turn on Focus Mode and restart DevTools
4. Open React DevTools tab "⚛️ Components"
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1001890/228293575-ca1b29a8-6126-44f8-bb45-51d9a7c8dc93.png">
5. Go to a different panel (e.g. Network)
6. Got back to  "⚛️ Components", see the page is blank and says "Unable to find React on the page."
<img width="425" alt="image" src="https://user-images.githubusercontent.com/1001890/228293902-4d5b8124-569e-4729-aaf2-714d554db5ab.png">

The text "Unable to find React on the page." is the raw state of panel.html. The extension adds a listener (`extensionPanel.onShown.addListener`) to construct this panel. It seems that the state of the panel is destroyed when switched away.

AB#43958456

**Comment by captainbrosset** [comment]
We have news to share on this! This is now fixed and you can check it out with the Canary version of Microsoft Edge (or just wait for the fix to make its way through our various pre-release channels: Canary -> Dev -> Beta -> Release).
