### ISSUE TITLE
add rumble channels to collection

### ISSUE THREAD

**Issue by EyalYe** [MicrosoftEdge/DevTools#141]
I like the collection feature and the ability to follow YouTube channels on the following tab on the collection tab can you add the ability to follow rumble channels as well?

**Comment by captainbrosset** [comment]
This repository is specific to DevTools. DevTools is a developer feature in Edge which has nothing to do with tabs or collections.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
