### ISSUE TITLE
Please add a Setting to disable the Back button on tabs opened from 'Open Link in New Tab'

### ISSUE THREAD

**Issue by dropdx** [MicrosoftEdge/DevTools#144]
I'm on a MacBook Air M1 and on a website when I right click a link and go to `Open Link in New Tab`, when I'm on the other page, I'll sometimes need to swipe right on the touchpad, not even hard, maybe just to scroll over or some other reason, and even though it's a new tab the back button is still active but it just closes the tab.

I get that some people might find this useful for quick browsing, but it's seriously killing me. It keeps happening and I keep needing to reopen the tab.

I have the close tab on double click turned on, and that works great for me. I don't want swiping right to close the tab! 

Please add a Setting for this!

Thanks

**Comment by captainbrosset** [comment]
I understand the feedback. Thanks for submitting it. But This repository is specific to DevTools. DevTools is a developer feature in Edge which is not related to tabs or navigation.

Could you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
