### ISSUE TITLE
Inconsistant Box Sizing on 3d View.

### ISSUE THREAD

**Issue by SilentPenguin** [MicrosoftEdge/DevTools#146]
Recently discovered that some elements will be reported as significantly larger on 3d view than anywhere else in devtools.

For example, on the hertfordshire county council homepage located at [https://www.hertfordshire.gov.uk/home.aspx](https://www.hertfordshire.gov.uk/home.aspx), the 3d view will report elements will extend thousands of pixels across the left margin, while the rest of the devtools does not.

![image](https://user-images.githubusercontent.com/186290/235111899-b82d3fd5-e455-4ab2-af41-ff17f1e12f4e.png)

However, elsewhere in the devtools, this discrepency is not visible.

![image](https://user-images.githubusercontent.com/186290/235112455-73b58b9b-82e1-4afd-bbe3-9e3d89e6bcf4.png)
![image](https://user-images.githubusercontent.com/186290/235112951-a20bfc50-9cd7-4ce7-b8e3-2f16fc9ec96f.png)

Many thanks.

AB#44485044

**Comment by captainbrosset** [comment]
Thanks for reporting this bug, and providing so many details! I'll make sure this shows up on our team's radar for investigation.

**Comment by captainbrosset** [comment]
> the 3d view will report elements will extend thousands of pixels across the left margin

Something to keep in mind though: the screenshot you posted shows the **Composited Layers** tab in the 3D View tool. This tab shows the graphic layers created by the browser's rendering engine, not the DOM elements.

So, it's perfectly normal that these layers don't match the elements on the page. Now, as to why this particular layer extends far to the left, outside the viewport, is probably something worth investigating.
