### ISSUE TITLE
Search the console option doesn't search for entire error message

### ISSUE THREAD

**Issue by AndeYashwanth** [MicrosoftEdge/DevTools#148]
https://microsoftedge.github.io/DevTools/explainers/SearchConsole/explainer
When I click on search icon next to the error messages in edge console, it doesn't search for entire error message.
For example below are three error messages from my angular application and their search url's when I click the search icon.
- https://www.bing.com/search?q=ERROR
- https://www.bing.com/search?q=Failed%20to%20load%20resource
- https://www.bing.com/search?q=ERROR
```js
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'sortBy')
TypeError: Cannot read properties of null (reading 'sortBy')
    at xxxx.component.ts:118:54
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at asyncToGenerator.js:27:1
    at new ZoneAwarePromise (zone.js:1351:25)
    at asyncToGenerator.js:19:1


Failed to load resource: the server responded with a status of 500 ()


ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[DashboardService -> DashboardService -> DashboardService]: 
NullInjectorError: No provider for DashboardService!
NullInjectorError: R3InjectorError(AppModule)[DashboardService -> DashboardService -> DashboardService]: 
NullInjectorError: No provider for DashboardService!
    at NullInjector.get (core.mjs:7599:27)
    at R3Injector.get (core.mjs:8020:33)
    at R3Injector.get (core.mjs:8020:33)
    at R3Injector.get (core.mjs:8020:33)
    at ChainedInjector.get (core.mjs:12179:36)
    at lookupTokenUsingModuleInjector (core.mjs:3255:39)
    at getOrCreateInjectable (core.mjs:3300:12)
    at Module.ɵɵdirectiveInject (core.mjs:10135:12)
```
As you can see it just searches for `ERROR` instead of entire message `ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'sortBy')`. Same is the case for other messages.

AB#44527415

**Comment by captainbrosset** [comment]
Oh, that's not a great experience indeed.
Thank you for reporting this bug. I'll make sure the dev team knows about it and takes a look.
