### ISSUE TITLE
Icon visibility, as well as, quick link arrow to disappear for UI ease

### ISSUE THREAD

**Issue by Renfrew100** [MicrosoftEdge/DevTools#149]
**Problem statement:**
-The navbar contains icons that disappear once scrolled down to the bottom of the page. (see figure 3)
-Have to open up "QuickLinks" to make the icons appear as well (see figure 1)

**Illustration of Frustration:**
![image](https://user-images.githubusercontent.com/37605427/236932987-d499e6ff-37e9-423a-9abb-335792b854e4.png)
_**Figure 1**_

![image](https://user-images.githubusercontent.com/37605427/236931325-270ca4d8-eb4e-47e8-ac51-1689708479cd.png)
_**Figure 2**_

 -Contains an image of the icons disappearing when scrolled down to the bottom of the page

![image](https://user-images.githubusercontent.com/37605427/236931390-5ebd801a-9d41-4870-b112-9ff80c256e16.png) 
**_Figure 3_**

![image](https://user-images.githubusercontent.com/37605427/236936874-13362b5b-0121-40a2-b98f-b81be069b0ba.png)
_**Figure 4**_

![image](https://user-images.githubusercontent.com/37605427/236937138-bd8e2c68-9ec9-487b-b5a8-683d05a580a5.png)
_**Figure 5**_

**Proposal:**
-Change up source code to get rid of "action-button action-button-rmbp class" for the quick links (figure 4)
-As well as, make the icons appear instead by keeping figure 5 in illustration of frustration.

**Comment by captainbrosset** [comment]
This repository is specific to DevTools. DevTools is a developer feature in Edge which is separate from the Edge new tab page.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
