### ISSUE TITLE
Audio/Sound toggle Feature in Site Setting!

### ISSUE THREAD

**Issue by uttamkoirala** [MicrosoftEdge/DevTools#151]
There isn't audio/sound toggle in site setting like in Google Chrome!

**Comment by captainbrosset** [comment]
This repository is specific to DevTools. DevTools is a developer feature in Edge unrelated to the browser settings.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
