### ISSUE TITLE
Experimental web platform features break text selection inside devtools

### ISSUE THREAD

**Issue by WRFan** [MicrosoftEdge/DevTools#152]
if the "enable-experimental-web-platform-features" is enabled, either passed on the command-line as an argument, or set in "edge://flags/", ANY selected text inside devtools becomes invisible. It's like the selection colour is transparent, so you can't see what you've selected. The problem occurs everywhere, be it when selectors are selected on the Elements tab, or you type something into a filter window (on the console tab etc.) and try to select what you typed, it's invisible. Took me some time to find what causes it.

*This part was moved to a new issue as asked by the admin*

Also, your new devtools which can be enabled as an experimental feature features a lower pane which cannot be permanently disabled, every time devtools are re-opened, it's there again. I am not going to use the new version of devtools until you allow to disable it permanently, because it steals space, especially inside a Hyper-V terminal, which is small as it is.

AB#44676348

**Comment by captainbrosset** [comment]
Thanks for reporting the text selection problem. I'll make sure it's on the team's radar for investigation/prioritization.

Thank you also for your questions around background requests that DevTools makes. If possible, could you please remove them from this issue and add them to a new, separate, issue instead? It makes things a lot easier when each issue is focused on just one topic. Thanks for your understanding!

**Comment by leahmsft** [comment]
Can't repro, closing for now
