### ISSUE TITLE
Conditional breakpoints should have a different color

### ISSUE THREAD

**Issue by harith1996** [MicrosoftEdge/DevTools#155]
Hello,
It would be good to make **conditional breakpoints** look different from the normal red-coloured breakpoints. This is a feature that is implemented in almost all Chromium-based browsers and Firefox, for example.

AB#44758899

**Comment by captainbrosset** [comment]
Thanks a lot for filing this. Let me make sure this is tracked by the team so it gets prioritized.
We'll make sure to come back here and comment when we have any updates to share.

**Comment by leahmsft** [comment]
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2024/09/devtools-129#unique-icons-for-logpoint-and-conditional-breakpoints
