### ISSUE TITLE
关于Drop的一个想法

### ISSUE THREAD

**Issue by qinzhe1993** [MicrosoftEdge/DevTools#157]
是否可以将edge浏览器内置的drop功能，做成独立的windows应用，使它不仅支持在线发送文档，还能支持局域网传输，同时还具有云存储功能

---

Translation using Google Translate:

Is it possible to make the built-in drop function of the edge browser into an independent windows application, so that it not only supports online sending of documents, but also supports LAN transmission, and also has cloud storage function

**Comment by captainbrosset** [comment]
Thank you for your question. However, this repository is specific to DevTools. DevTools is a developer feature in Edge which is unrelated to Drop.
Can you please send your feedback again by using the browser's feedback mechanism instead? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.

---

Translation using Google Translate:

谢谢你的问题。 但是，此存储库特定于 DevTools。 DevTools 是 Edge 中的开发人员功能，与 Drop 无关。
您能否改用浏览器的反馈机制再次发送您的反馈？ 就是这样：

1. 单击**设置和更多**（浏览器右上角的“...”按钮）。
2. 单击**帮助和反馈**。
3. 单击**发送反馈**。

感谢您的理解。
