### ISSUE TITLE
Can't move, minimize, or maximize devtools

### ISSUE THREAD

**Issue by fbbDirge** [MicrosoftEdge/DevTools#158]
![image](https://github.com/MicrosoftEdge/DevTools/assets/86771432/3c11e5d0-cf39-4671-a48a-2f1931d49c22)
My debugging tool has an exception, how can I solve it, I found that my dev version of the edge browser cannot maximize and minimize me
In the left part of the figure, the right side is the official version of the debugging tool, how can I solve my problem, please help me

AB#44916962

**Comment by captainbrosset** [comment]
Thank you for reaching out and providing this screenshot. I can reproduce too. I'll make sure our dev team is aware of this and works onj the issue. This is definitely a bug on our side.

**Comment by captainbrosset** [comment]
I checked with the team and they've actually already fixed it in Canary. They will make sure the fix makes it to the Dev version too.
