### ISSUE TITLE
Can't see .har webrequests info when importing .har files in Edge 114

### ISSUE THREAD

**Issue by corrado49** [MicrosoftEdge/DevTools#161]
When upgrade to Edge Version 114.0.1823.41 the upload of .har files is not working correctly. Can not see the requests info, however can see the overview section populated.

I have repro the issue in many machines. Btw Edge 113 works.

Repro steps:
Open Edge
go to settings - developer tools
capture some requests and save as .har file
stop the capture and clear

then click on upload 
select .har file saved before
will see that you can see the summary but not the requests information

![Screenshot 2023-06-07 190152](https://github.com/MicrosoftEdge/DevTools/assets/40476641/56f9c5ab-9e6c-44e2-ac5d-15342a3932ec)

AB#44981472

**Comment by Yvand** [comment]
I face exactly the same issue on Edge `114.0.1823.41 (Official build) (64-bit)`

**Comment by leotlee** [comment]
This is a known Chromium bug that was just recently fixed, Edge 114 should have the fix next week..

[1450622 - Requests from uploaded HAR file are not displayed - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1450622)

**Comment by corrado49** [comment]
Good! thanks for letting us know.
