### ISSUE TITLE
Support for AVIF image format in Microsoft Edge

### ISSUE THREAD

**Issue by DCruz-FS** [MicrosoftEdge/DevTools#164]
As AVIF aims to address every conceivable use case for raster images on the web: GIF-like animation, PNG-like transparency, and improved perceptual quality at file sizes smaller than JPEG or WebP. This would improve the image quality, increase the download speeds and improve user experience.

**Comment by captainbrosset** [comment]
Thanks for reaching out. This request is for the whole browser, however our repository here is only for DevTools, which is a subset of the browser only.
I know this is an important topic that's already tracked by the browser team, but I would advise you to send your feedback to them again:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
