### ISSUE TITLE
Problem with gps coordinates after recent update of Edge

### ISSUE THREAD

**Issue by Krone-Big-X** [MicrosoftEdge/DevTools#165]
Hello,

We are currently using the Geolocation API to get exact coordinates from a DELL Toughpad 7212 with an external gps device (GPS-Mouse "Navilock NL-8012U USB Multi GNSS"). We are using a LTE-Box from Huawai to connect the tablet with the internet (no WLAN). The operating system on the tablet is an up to date Windows 10.
Until Edge 112.0.1722.68 we were receiving gps coordinates without any problems and with a accuracy <= 5 meters.
With Edge 114.0.1823.37 the accuracy varies from 20 up to 100 meters (on an open test area in Spelle, Germany).
Using Firefox (or u-blox 8 to directly read from the gps device), we are getting accurate results (accuracy <= 5 meters).
We think, that Edge 114.0.1823.37 prioritises other (less accurate) gps sources than firefox.
We consider this a bug, because the browser should always use the most accurate gps-coordinates.

Sincerely

**Comment by captainbrosset** [comment]
Thank you for reaching out and submitting this feedback. This repository, however, is specific to DevTools only. DevTools is a developer feature in Edge which is separate from how the Geolocation API is implemented in the Edge browser. So, your feedback is very useful, but unfortunately this isn't the right place for it.

Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
