### ISSUE TITLE
Edge Dev's video decoding has issues when playing videos on bilibili.

### ISSUE THREAD

**Issue by MiyagawaMizu** [MicrosoftEdge/DevTools#167]
Edge Dev's video decoding has issues when playing videos on **https://www.bilibili.com/**. the videos are very laggy and have green glitch.
Version 116.0.1938.23 (Official build) dev (64-bit)

**Comment by captainbrosset** [comment]
This repository is specific to DevTools. DevTools is a developer feature in Edge which is unrelated to how videos are decoded in Edge.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
