### ISSUE TITLE
JSON Viewer doesn't render anything for IAsyncEnumerable<T> APIs

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftEdge/DevTools#168]
I am testing a few IAsyncEnumerable<T> APIs to a web application. 
Rendering these APIs works well only when I turn off the JSON Viewer flag in edge. 
With this enabled it never renders any information, until I basically kill the stream.

_Originally posted by @juscla in https://github.com/MicrosoftEdge/DevTools/issues/87#issuecomment-1644303438_
            

AB#45638852

**Comment by captainbrosset** [comment]
@juscla, do you have any other information you share by chance?
I don't suppose you have a URL to the API endpoint that we could use? Any sample app out there that might replicate the issue? Or source code we could look at?

**Comment by leahmsft** [comment]
Closing since JSON Viewer has been deprecated and removed from Microsoft Edge.
