### ISSUE TITLE
Edge and Firefox handle CRL and AIA information in digital certificates differently

### ISSUE THREAD

**Issue by yupeijian9** [MicrosoftEdge/DevTools#177]
user agent(Edge):Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69
Operating System: Windows 10 22H2 19045.2604

Overview: We tested with a mutated digital certificate as a test case. We found that Firefox can parse and display the CRL and Authority Information Access (AIA) information of the certificate, but Edge cannot parse them. 

Steps to Reproduce: 
(1) In Firefox, visit the url about:certificate?cert=(processed pem data) containing the certificate information.
(2) Use Python to create a local server (e.g. using Flask) and specify a mutated certificate and private key. Access the Flask provided url in Edge.

Actual Result: Edge cannot parse and display the CRL and AIA information of the certificate. Firefox can parse and display them.

Expected Result: Edge should be able to parse and display the CRL and AIA information of the certificate like Firefox, and the information should be consistent.
![crl_diff_firefox](https://github.com/MicrosoftEdge/DevTools/assets/50319060/a4c601ae-3481-464e-926b-2d31cbae7ba2)
![aia_diff_firefox png](https://github.com/MicrosoftEdge/DevTools/assets/50319060/04facd1e-9915-48d9-85fb-862313410163)
![aia_diff_edge](https://github.com/MicrosoftEdge/DevTools/assets/50319060/9c0aa5e7-b2f8-4eeb-87ad-a583a02cc411)
![crl_diff_edge](https://github.com/MicrosoftEdge/DevTools/assets/50319060/7b187388-f436-495c-9f7a-74410f76e1e8)
[cert_file.zip](https://github.com/MicrosoftEdge/DevTools/files/12544182/cert_file.zip)

**Comment by captainbrosset** [comment]
Thanks for reaching out and providing this much information.

Unfortunately, this repository is specific to DevTools. DevTools is a developer feature in Edge which has nothing to do with how Edge processes certificates.
The best course of action for your feedback would be to use the Feedback Dialog in Edge:

So, can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
