### ISSUE TITLE
Switching between collections shortcuts

### ISSUE THREAD

**Issue by iamgm** [MicrosoftEdge/DevTools#178]
Hi, 
I have feature request

NOW
to open collection, I need:
- press ctrl + shift + y
- scroll collections using mouse
- right click on chosen collection
- press "Open all (10)"
   or press "Open all (10) in new window"

EXPECTED BEHAVIOR
It would be nice if I can do it this way: 
- press ctrl + shift + y
- scroll collections using arrow keys 
- press enter on chosen collection to "Open all (10)"
- press ctrl + enter to "Open all (10) in new window"

**Comment by captainbrosset** [comment]
This is a very nice feature request, and I could see myself using this too. But, unfortunately, this repository is for DevTools. DevTools is a developer feature built into Edge which has nothing to do with the browser UI, including collections.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.

**Comment by iamgm** [comment]
Ok.  I've got it. Thanks for advice!
