### ISSUE TITLE
Network throttling defaults to offline

### ISSUE THREAD

**Issue by smurawski** [MicrosoftEdge/DevTools#179]
After updating to Version 116.0.1938.76 (Official build) (64-bit), when opening the network tools, the network throttling defaults to "offline", which was unexpected.

This was confirmed on three separate machines, one which was behind one update and behaved as expected, then defaulted to offline after the update.

AB#46510687

**Comment by captainbrosset** [comment]
Thanks a lot for reporting this. I will make sure this shows up on our team's roadmap. I personally don't have that bug. Was this on Windows, macos, linux? Different OSes?

**Comment by captainbrosset** [comment]
Quick status update: our team is top of this and working on a fix that should hopefully make it to the upcoming releases of Edge.

**Comment by smurawski** [comment]
> Thanks a lot for reporting this. I will make sure this shows up on our team's roadmap. I personally don't have that bug. Was this on Windows, macos, linux? Different OSes? If you switch the throttling selectbox to "no throttling", does it stay this way, or does it always go back to offline when you restart DevTools?

Sorry, I missed this update and question - It was on Windows and the setting seems to stay once the change was made.

**Comment by captainbrosset** [comment]
As far as I can see, a fix has been made to Edge 118, and also applied to 117. So, in theory, the bug should now be fixed. I'll therefore go ahead and close this issue. But, please, do re-open/comment if you see the problem still.
