### ISSUE TITLE
Dark Mode Language Selection Dropdown UI Bug

### ISSUE THREAD

**Issue by bilalmirza74** [MicrosoftEdge/DevTools#180]
UI of the search page on Edge Browser in Dark Mood/Theam
The language Selection Dropdown is not visible Properly 
,

![image](https://github.com/MicrosoftEdge/DevTools/assets/84387676/a2a5cd94-a8f7-4dd1-9765-81f8ca693565)

**Comment by captainbrosset** [comment]
Hey @bilalmirza74, thanks for reaching out and reporting this.
Can you help me understand the issue a bit better? What exactly do you mean by the "search page"? Is that the new tab page in Edge, or something in DevTools? If you can, please post a screenshot that shows the entire search page. This would make it easier for me to understand the exact issue.

**Comment by captainbrosset** [comment]
Thank you for providing these additional details. I now understand the issue.

This repository is specific to DevTools. DevTools is a developer feature in Edge which is unrelated to the way the bing.com website appears.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
