### ISSUE TITLE
Open new tabs on top (vertical tabs)

### ISSUE THREAD

**Issue by gonzalc** [MicrosoftEdge/DevTools#182]
I would like the capability to toggle whether new tabs are opened on the top/bottom of my vertical tabs.

# current
- existing tab
- existing tab
- new tab

# suggested
- new tab
- existing tab
- existing tab

**Comment by captainbrosset** [comment]
Hello. Just to double-check, because this isn't clear to me: is this about the Edge browser tabs, or about the tool tabs within DevTools?

**Comment by gonzalc** [comment]
This question is related to the Edge browser tabs.

**Comment by captainbrosset** [comment]
Ah ok, in that case you're not in the right place. This repository is for DevTools, which is a built-in tool within Edge, for developers.
For any feedback regarding the browser itself, please use the browser feedback tool instead, here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
