### ISSUE TITLE
Automatic update causes out of mac version support

### ISSUE THREAD

**Issue by zongdeiqianxing** [MicrosoftEdge/DevTools#184]
After edge automatically updated a few days ago, my 10.14 mac system said it was unavailable because it required a minimum 10.15 operating system version.
Therefore, please provide the ability to turn off automatic updates, or similar to chrome, the software checks in the background to see if the system version supports it before pushing updates

**Comment by zongdeiqianxing** [comment]
<img width="474" alt="edge" src="https://github.com/MicrosoftEdge/DevTools/assets/34082644/f2e3b82d-c363-4a34-9fef-24b349bdd862">
Now it updates automatically again, if you can, please fix it as soon as possible

**Comment by captainbrosset** [comment]
Sorry you are facing this issue. Unfortunately, this repository isn' the right place to report this problem.
This repo is focused on DevTools, a suite of tools for web developers to debug their websites. DevTools is only a sub-part of Microsoft Edge.

Can you please submit your feedback again by using the browser's feedback tool instead? Here is how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
