### ISSUE TITLE
bug/bluf

### ISSUE THREAD

**Issue by markjpT** [MicrosoftEdge/DevTools#187]
[artifacts_v1_asn_sample.csv](https://github.com/MicrosoftEdge/DevTools/files/12826989/artifacts_v1_asn_sample.csv)
[files_d3c948f2b1a37e6cdce97fd33f2951f3.zip](https://github.com/MicrosoftEdge/DevTools/files/12826990/files_d3c948f2b1a37e6cdce97fd33f2951f3.zip)
[files_81304df45e093f925093d421d8d1ebf9.zip](https://github.com/MicrosoftEdge/DevTools/files/12826991/files_81304df45e093f925093d421d8d1ebf9.zip)
[files_f527d9c4fcfe92a9a2cc85387c7fb860.zip](https://github.com/MicrosoftEdge/DevTools/files/12826992/files_f527d9c4fcfe92a9a2cc85387c7fb860.zip)

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
