### ISSUE TITLE
Connection Type of "Chrome devtools protocol websocket (no authentication)" lost in Attach to process Dialog

### ISSUE THREAD

**Issue by karltsc** [MicrosoftEdge/DevTools#188]
Hello, when i install both VisualStudio2019 and VisualStudio2022,  Connection Type of "Chrome devtools protocol websocket (no authentication)"  only exists in one of the installation. how can is install the debugger manually, since i need to debug javascript code running in an app that v8 is embeded.   all javascript/nodejs related items has been installed.

**Comment by captainbrosset** [comment]
Thanks for reaching out. However, I believe you will have better luck getting this question answered on the Visual Studio Developer Community, here: https://developercommunity.visualstudio.com/VisualStudio

You can search for "devtools protocol websocket" and see if there are similar questions already, or you can report a new issue!
