### ISSUE TITLE
In DevTools,the reading of the splice attribute can be detected

### ISSUE THREAD

**Issue by maizi20** [MicrosoftEdge/DevTools#193]
When the developer tool opens, it automatically reads the 'splice' property of most object types on the console and triggers the getter.

This feature can be used for interference with developer tools and can not be prevented by scripting.

For example:
```
console.log({
   get splice(){
     location.replace('about:blank')
     //If the console is already open, the splice property of this object will be read and redirected to an empty page.


   }
})
```

A similar problem exists with the code debugger:
```
!function(){
  var o={get splice(){location.replace('about:blank')}};
  debugger //When you debug here, redirection is triggered by reading the splice property to the object in scope.
}()
```

(There is no such bug in Firefox.)

AB#47199348

**Comment by captainbrosset** [comment]
Thanks a lot!

**Comment by sethbrenith** [comment]
Thanks for reporting! This bug is [now fixed in V8](https://chromiumdash.appspot.com/commit/63c5122d294380ff27f17eba63d82b2f4a201f83), so the fix should be available in the upcoming version 121 of Edge and Chrome.

**Comment by captainbrosset** [comment]
Pre-emptively closing this issue based on Seth's message (otherwise I'll forget and it will remain open forever 😄).
But feel free to re-open if the problem persists.
