### ISSUE TITLE
Json Viewer improvements: VSCode theme, large font-size and line-height, and size of JSON data

### ISSUE THREAD

**Issue by imprathamesh** [MicrosoftEdge/DevTools#194]
I would like to suggest this feature might be helpful to every developer 
1. Json Viewer theme - must include the vs theme style colors for key and value
2. Line-height and font size - font size 14 and line height should be 1.5 It will be increase the readability. 
3. Show the size of json about the each curly bracket and total size of json.

hope this will be update soon.

Regards, 
Prathamesh Shende

AB#47237817

**Comment by captainbrosset** [comment]
Thank you for the feature request. These improvements sound good to me. I'll make sure this item is added to our backlog for future prioritization and implementation.

**Comment by leahmsft** [comment]
Closing since JSON Viewer has been deprecated and removed from Microsoft Edge.
