### ISSUE TITLE
Could I get Edge's rendering results？

### ISSUE THREAD

**Issue by FanetheDivine** [MicrosoftEdge/DevTools#195]
It's hard to store doms as pictures or videos without html2canvas. That will be easy if some APIs to get rendering results of specific doms are accessible

**Comment by captainbrosset** [comment]
Hey @FanetheDivine. I need more details to fully understand the scenario here. Can you say more about what you want to do exactly, and why? Also, why is html2canvas not a good option for you?

This reminds me of a couple of other features which you might want to explore:

* https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture
* https://chromestatus.com/feature/5198989277790208

Also, unfortunately this is the DevTools repo, not a repo for Edge in general. So, this isn't the right venue for this request. I suggest reaching out again by using the browser feedback tool instead. Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.

**Comment by FanetheDivine** [comment]
@captainbrosset Thanks for your suggestion. The reason I need rendering results is that I'm trying to silently record the user's actions in the form of screenshots. In addition, I also want to use the browser rendering engine to make animations. `getDisplayMedia` requires user interaction and cannot select the current page. `html2canvas` has some performance problems and incomplete CSS support. They are a little different from what I want.
And then I will give feedback directly in Edge
