### ISSUE TITLE
Ability to pin extensions in title bar for "App" webpages

### ISSUE THREAD

**Issue by waronhate** [MicrosoftEdge/DevTools#198]
Having access to extensions on webpages that were "installed as an app" would be very helpful. For example, I do not have quick access to my password manager's menu without having to dig through the "..." submenus.

**Comment by captainbrosset** [comment]
Thanks for your feedback. This repository is specific to DevTools however. DevTools is a developer feature in Edge which is unrelated to extensions or installed apps.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
