### ISSUE TITLE
DevTools tab not opening -  Related to pt-BR main language.

### ISSUE THREAD

**Issue by Victorhtf** [MicrosoftEdge/DevTools#200]
Suddenly my DevTools tab stopped working. I mean, its not showing when I hit F12 or when I click in inspect element. I already checked if its activated in Edge configurations and it is.  I hit the inspect element button and nothing happens, its like it was oppening, but its not. Its not working in all web pages.

My DevTools its supposed to appear in a new tab, it was working until yesterday, then suddenly stopped, I not even update nothing in my notebook.  I'm in v120.0.2210.7.

 I tried to perform a repair in Edge application, restart computer and I also tried some solutions in Powershell, tried to delete the Edge Folder in Packages folder, reset the browser settings, all without success.
 
  I'm in Edge v120.0.2210.7. Stable, beta channel of Insider. 
 

AB#47706800

**Comment by renanlido** [comment]
The same problem here.

I tried the same strategies to repair, but all without success to.

**Comment by Victorhtf** [comment]
Renan, I have seen your surname and recognize as a Brazilian....I discovered how to fix it...for some reason when I hit the DevTool using the portuguese-brazilian as Edge primary language it does not show up.

But I have tried to switch for English and then it worked....can you try in your browser too? Go to "languages" (Idiomas) > "preferred languages" then hit the more options in English tab and set up English as your browser main language.

![image](https://github.com/MicrosoftEdge/DevTools/assets/126508458/50739162-a15f-4be5-8747-58b7358d05d8)

**Comment by Victorhtf** [comment]
I have tried to switch my browser languages to other such as French, Spanish and UK english...All of them looks good, F12 hit and inspect button working. Just in Portuguese - Brazilian its not.

**Comment by renanlido** [comment]
Thanks @Victorhtf! It worked wonderfully.

**Comment by captainbrosset** [comment]
Many people will be thankful to you for reporting this bug, even if they never know what happened :)

**Comment by marcelgrilo** [comment]
> Renan, I have seen your surname and recognize as a Brazilian....I discovered how to fix it...for some reason when I hit the DevTool using the portuguese-brazilian as Edge primary language it does not show up.
> 
> But I have tried to switch for English and then it worked....can you try in your browser too? Go to "languages" (Idiomas) > "preferred languages" then hit the more options in English tab and set up English as your browser main language.
> 
> ![image](https://private-user-images.githubusercontent.com/126508458/283813984-50739162-a15f-4be5-8747-58b7358d05d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MzgyMDAsIm5iZiI6MTcwMDkzNzkwMCwicGF0aCI6Ii8xMjY1MDg0NTgvMjgzODEzOTg0LTUwNzM5MTYyLWExNWYtNGJlNS04NzQ3LTU4YjczNThkMDVkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxODQ1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTgzNTAxODMwMDRkOGQxODcwMWM3MDgyMGRlMGRkMzNmZTk5NjYwMmQ2NDRmMzU2ZTExYTAxYmI4NTlkNmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ewld4tzZz7jeobv6T_vzu9sxn8x-RZq49An6CzeMlGA)

it worked for me, thank you verry mutch!!!

**Comment by maisondasilva** [comment]
Thank you for reporting this, I had reported it on Microsoft's Tech Community and also discovered that changing the language solved the problem, especially because several of my friends who used English were fine. The problem for me affects all channels including the new version in Canary 121

https://techcommunity.microsoft.com/t5/discussions/after-version-120-in-beta-dev-and-canary-opening-the-developer/m-p/3982819

**Comment by maisondasilva** [comment]
@Victorhtf Do you have an account at Mercado Livre? I noticed that when this problem appeared, the email address entered into the Mercado Livre account did not work!

![image](https://github.com/MicrosoftEdge/DevTools/assets/11423362/a74dd59d-d6d3-4c8b-a5c1-96f5bea845da)

**Comment by renanlido** [comment]
@maisondasilva this problem also occurred to me.

**Comment by captainbrosset** [comment]
I think this is a different problem @maisondasilva. It occurs to me too, even if my browser is in English.
It seems to work on Firefox and Chrome, but not on Edge. This might be a problem with the site itself, not with Edge. But I'm not sure yet.
In any case, this isn't related to this current issue. Can you please send this feedback via the browser feedback tool:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thanks!

**Comment by captainbrosset** [comment]
I won't investigate this further, but this indeed seems to be a problem with the site itself. There's a script called NRWrapper which is downloaded on other browser but not on Edge. And it seems to be responsible for handling user events in some way. Because it's missing in Edge, the keyboard events that get triggered when you type your email address don't do anything, and therefore the button doesn't become blue. I would suggest reaching out to the site's customer support line (if they have one) and letting them know.

**Comment by maisondasilva** [comment]
Thanks for your full report, I only reported it here because it appeared the same day I noticed that DevTools wasn't opening, anyway I had already contacted the site developers and sent them a hub on Edge too, as I didn't know which side it was coming from the problem. Thank you very much @captainbrosset

**Comment by maisondasilva** [comment]
@captainbrosset The strangest thing is that in version 119 of Edge which is not affected by the bug "DevTools", I have now tested the site and it works as expected.

![image](https://github.com/MicrosoftEdge/DevTools/assets/11423362/bddfb7cd-d618-4b86-9980-3668272a12e6)

**Comment by renanlido** [comment]
> @renanlido Does it still happen, or how did it resolve?

 Does it still happen.

**Comment by raphaelquati** [comment]
> Thanks for your full report, I only reported it here because it appeared the same day I noticed that DevTools wasn't opening, anyway I had already contacted the site developers and sent them a hub on Edge too, as I didn't know which side it was coming from the problem. Thank you very much @captainbrosset

Same here. After dev tools stop working, Mercado Livre site stops working.
After changing the language, DevTools is working now. But Mercado Livre site still not working

Accessing Mercado Livre, in console shows an error only in Edge:

```
The resource https://www.recaptcha.net/recaptcha/enterprise.js?onload=onloadCallback&render=6LeetcMeAAAAAHBLMG_uCF4A7QLR8ZHg8u4ulR5z&hl=pt-BR was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally. 
```

**Comment by maisondasilva** [comment]
Version 121.0.2263.0 (Official build) canary (64 bits) the developer tool already works for me!

**Comment by renanlido** [comment]
https://github.com/MicrosoftEdge/DevTools/issues/200#issuecomment-1841349642 - Worked for me too. But, the Mercado Livre it`s still not working. Very strange.... Any suggestions?

**Comment by maisondasilva** [comment]
Yes, even for me, I'm sending a DM message to the free market and paid market to see what happens!

**Comment by maisondasilva** [comment]
I would like to inform you that Mercado Livre has already corrected it in Microsoft Edge, thanks for the additional information @captainbrosset

**Comment by captainbrosset** [comment]
That's awesome. Thanks for closing the loop here.
