### ISSUE TITLE
Application Tab Blank

### ISSUE THREAD

**Issue by phuoctaiismee** [MicrosoftEdge/DevTools#201]
![image](https://github.com/MicrosoftEdge/DevTools/assets/113773744/fe7013a2-cd05-4150-982e-afa6a1cb860e)
I can't check localStorage, Cookie,...
I updated to the latest version, reset default Edge and Repair but it's still blank in that tab

**Comment by captainbrosset** [comment]
Closing as a duplicate of #199. Please see that other issue for latest status on this.
