### ISSUE TITLE
Translate function

### ISSUE THREAD

**Issue by RyansBello** [MicrosoftEdge/DevTools#204]
Im almostly translate for web that describe the code i need to learn. For regular web (only text) translate is just perfect using Edge Translator tools but when web with code snipped (stackoverflow or simmilar) the code snipped goes to the end of paragraf and makes hard to understand tue contex. And honestly, i have to move to chrome to understand the contex translate correctly.
Im hope that bug can be fixed. 
Thank you

**Comment by captainbrosset** [comment]
Thank you for reaching out about this, and sorry about the problem. This seems frustrating.
This repository is specific to DevTools. DevTools is a developer feature in Edge which is unrelated to the Edge translator tools.
Could you please send your feedback again by using the browser's feedback mechanism instead? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
