### ISSUE TITLE
Майкрософт
Выберите учетную запись
Выделенная учетная запись пользователя не существует в клиенте "Microsoft Services" и не может обращаться к приложению "37cf8c88-a959-4826-8d1b-f466d1e573f1" в этом клиенте. Необходимо сначала добавить учетную запись в качестве внешнего пользователя для клиента. Используйте другую учетную запись.
	
qa vk
ivanmalikov394@icloud.com
Вход выполнен
Ошибка входа 

### ISSUE THREAD

**Issue by ivanmalikov394** [MicrosoftEdge/DevTools#207]
ivanmalikov394@icloud.com
This content has been deleted.
This content has been deleted for violating community guidelines.
Back to Q&A homepage
![Screenshot_2023-12-13-16-14-55-282_com.yandex.browser.jpg](https://github.com/MicrosoftEdge/DevTools/assets/92212226/3cce027f-fd54-46fe-ada2-fc5f25328bdd)

![Screenshot_2023-12-13-15-58-23-483_com.yandex.browser.jpg](https://github.com/MicrosoftEdge/DevTools/assets/92212226/2c3e6921-048e-4bf4-b86b-bd5c6eeedc83)

@microsoftopensource , help me 😭
@edge
@EDGE
@Edgi
[]()ivanmalikov394@icloud.com

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
