### ISSUE TITLE
Microsoft Editor integration in dev tools

### ISSUE THREAD

**Issue by nvmkpk** [MicrosoftEdge/DevTools#21]
Microsoft editor integration in dev tools messes up with anything I type in it. Right arrow should not auto complete whatever it suggests and should only work like how auto complete works in VS Code or Visual Studio.

**Comment by captainbrosset** [comment]
Hey, thanks for reaching out and filing this issue. I'd like to make sure I understand the problem clearly. Would you mind providing more info please? In particular, I'm not sure what you mean by "Microsoft editor integration". Could you elaborate please? Also, attaching an image of the exact problem, as well as steps to reproduce it, would help a lot!

**Comment by nvmkpk** [comment]
Open this link https://www.microsoftedgeinsider.com/en-us/whats-new and find the tile that talks about it (hint: press `Ctrl + F` and type `Microsoft Editor`). Unfortunately, I couldn't get a direct link to it.

**Comment by captainbrosset** [comment]
Oh I see, thanks a lot for providing this extra info.
So, since this is related to a browser feature, and not a devtools feature, could you please submit this feedback to the browser team by going to **Settings and more** (the `...` button) > **Help and feedback** > **Send feedback** ? That'd be awesome! Thank you.

**Comment by captainbrosset** [comment]
Oh I see. Can you please say more? Where exactly in DevTools does this occur? I've tried typing in the console, snippets, and edit-as-html, but didn't get the new editor feature from the browser. If you can, please give me a specific example of where you typed, and what you typed. I wonder if there's a way DevTools can simply disable the new type-ahead feature.

**Comment by nvmkpk** [comment]
I tried it on the style editor on the right of elements tab as well as in the sources tab. I wanted to make a video or screenshot but the recent dev channel update made the browser unusable. It just crashes on startup.
