### ISSUE TITLE
After "Select an element in the page to inspect it", DevTools won't auto show in the front

### ISSUE THREAD

**Issue by otomad** [MicrosoftEdge/DevTools#214]
> Microsoft Edge	121.0.2277.83

In the legacy DevTools UI, when using "Select an element in the page to inspect it" tool (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>) to select an element in the page, the DevTools window would be automatically brought to foreground window. This is very convenient.
However, in the new DevTools UI, its behavior seems to be weird. After selecting the element, the DevTools window must be manually shown in the foreground. It's too troublesome.

New DevTools UI:

https://github.com/MicrosoftEdge/DevTools/assets/56647156/f781a21f-dc75-4fe5-bc0f-a373fbcd6dbd

Legacy DevTools UI:

https://github.com/MicrosoftEdge/DevTools/assets/56647156/1b7c6c02-a3da-46c2-bd70-0f4c05c110a3

AB#48729054

**Comment by captainbrosset** [comment]
Confirmed, this works fine with the legacy UI, but not with the new UI. Marking as tracked so it shows up on our backlog.

**Comment by leahmsft** [comment]
No longer repros, closing for now
