### ISSUE TITLE
[BUG] Edge Edit image function bug report

### ISSUE THREAD

**Issue by LiWeny16** [MicrosoftEdge/DevTools#216]
# [BUG] Edge Edit image function bug report
## Bug Content
+ On any webpage that can display IMG elements, right-click on the native function that appears, click on Edit Image. If you exit this page directly using ESC, the next time you enter, it will be stuck in circles and cannot be used. Only by clicking on the top right corner to exit can this function be used normally next time
+ Even if there is no editing of the image, clicking close will still pop up a save prompt

## OS
+ Windows 10 22H2
+ 121.0.2277.83 (正式版本) (64 位)

**Comment by captainbrosset** [comment]
Thanks for the report, unfortunately this was sent to the wrong place. This repository is specific to DevTools. DevTools is a web-developer tool that's built-in to Edge and which you can open by pressing F12 on any webpage.
The image edition feature of Edge is not related to DevTools and is maintained by a different team.

In order for your feedback to go to the right people, would you please re-submit it by using the browser Feedback tool? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
