### ISSUE TITLE
The output text of nested "console.group()" is overlapping.

### ISSUE THREAD

**Issue by experdot** [MicrosoftEdge/DevTools#218]
Run the following code in Console:
``` javascript
console.group("Group Name");
console.group("Group Name1");
console.group("Group Name2");
console.group("Group Name3");
console.log("Text 11");
console.log("Text 12");
console.groupEnd();
console.groupEnd();
console.groupEnd();
console.groupEnd();
```

The indentation and line height of the input text are both incorrect, especially with some text overlapping. 
![image](https://github.com/MicrosoftEdge/DevTools/assets/9404172/41c68de8-0882-4660-b59b-ab2c42e9b2f8)

This seems to have become a problem only recently.
Version 121.0.2277.83 (Official build) (64-bit)

**Comment by captainbrosset** [comment]
Thank you for reporting this. I tested in Chrome and the issue also appears there. So this is an _upstream_ issue (i.e. in Chromium). Let me file a chromium bug to track it.

**Comment by captainbrosset** [comment]
This is now tracked upstream at: https://bugs.chromium.org/p/chromium/issues/detail?id=1523149

**Comment by captainbrosset** [comment]
The upstream bug has now been resolved. Yay!
So it's just a matter of time for Edge to get the fix too.
