### ISSUE TITLE
Pinch to Zoom and Scrolling on Ubuntu

### ISSUE THREAD

**Issue by arthurdls** [MicrosoftEdge/DevTools#221]
I've been using Microsoft edge on my personal computer running Windows ever since it was released and I am very happy about the changes it's undergone since then (tab saving, multiple workspace, tab grouping and themes etc). 

My work computer uses Ubuntu 22.04, and I have tried using Microsoft edge on it. However, as of right now, there are no options in the settings for enabling pinch to zoom-in, scroll speed settings, and smooth scrolling. It feels like Microsoft edge is incompatible with Ubuntu right now. 

I am visually impaired so pinch to zoom-in is essential for me. Smooth scrolling and scroll speed settings would be nice to have. Would it be possible to add these as features?

**Comment by captainbrosset** [comment]
Thanks for your feedback, however this repository is specific to DevTools only. DevTools is a developer feature in Edge which is unrelated to ping to zoom, and other browser UI features.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
