### ISSUE TITLE
[Explain error with Copilot] Flag not showing up on macOS

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftEdge/DevTools#226]
> Any thoughts on why the flag wouldn't show up on macOS? I haven't been able to find it in any of the release channels. It's definitely there (and very cool!) on a Windows 11 VM running Edge mainline.

_Originally posted by @phyllisstein in https://github.com/MicrosoftEdge/DevTools/issues/203#issuecomment-1936949386_
            

AB#48952537

**Comment by leotlee** [comment]
This is now enabled by default on all platforms including macOS.

**Comment by leotlee** [comment]
Closing this issue.
