### ISSUE TITLE
Question: Do we have support to Command Palette API?

### ISSUE THREAD

**Issue by ppcamp** [MicrosoftEdge/DevTools#230]
Basically, I was a chrome user and, accidentally, I've found this feature in Edge recently (after my migration). 

After a couple searches, it seems to have some functionalities, but in overall, it's not that great. Although, I was wondering that if you guys enable a simple API/doc, we could develop extensions to read from that bar and take actions basing in the selected suggestion. Some examples that we could do:

- we could incorporate the `!` from command bar (in devtools) directly in command palette, therefore, we could easily create and run snippets in every site (it's annoying using command palette just to open up devtools)
- we could change focus or something like that.

Anyway, there are infinites possibilities that will boost that up. So, we could have something great just like VScode does with command center bar.

**Comment by captainbrosset** [comment]
This is great feedback. Unfortunately, our team has decided to discontinue the Command Palette experiment and it will be removed from Microsoft Edge starting with version 123. Maintaining this experiment had become costly, usage was low, and it was also a lower priority for our team than many other things.
Thanks for your understanding.

**Comment by manizm** [comment]
The Arc browser has this feature being used like a hot potato!
It just makes things so much easier for power users

**Comment by johnW-ret** [comment]
Command Palette features should be re-introduced into `Ctrl` + `Shift` + `A` Search Tabs, much like the way `Alt` + `Space` PowerToys Run works.

As a user, I should be able to hit `Ctrl` + `Shift` + `A` and type 'Wallet' and be able to navigate to `edge://wallet` - even if it wasn't recently opened.

**Comment by BosTheCoder** [comment]
The closest approach to this is likely saving `edge://wallet` to Edge Favourites under `Wallet`. Then you can search bookmarks with `Ctrl + shift + O`.
