### ISSUE TITLE
Network traffic summary footer partially covering last request in Network tab

### ISSUE THREAD

**Issue by Svish** [MicrosoftEdge/DevTools#231]
The Network tab has a network traffic summary footer at the bottom. When the tab fills up with requests, this footer partially covers the last request and the scrollbar doesn't allow me to scroll further down to reveal it.

**Edge Version** 122.0.2365.52 (Official build) (64-bit)

![image](https://github.com/MicrosoftEdge/DevTools/assets/142162/308c25fe-fef6-45ec-a32c-beb6b4aafbc8)

AB#49190256

**Comment by captainbrosset** [comment]
Thank you for filing. I'll mark this as part of our backlog so that our dev team can investigate. Unfortunately so far, I've not been able to reproduce this myself.
Would you have a chance to test with Chrome DevTools too? I'm wondering if the same overlap happens there too.

**Comment by Svish** [comment]
Same issue in Chrome DevTools it seems:
![image](https://github.com/MicrosoftEdge/DevTools/assets/142162/a7e345ba-7dae-4bb7-a689-bb40db3b3b3e)

**Comment by captainbrosset** [comment]
Thanks for testing! Let me turn this into an upstream issue then.

**Comment by captainbrosset** [comment]
This issue is now tracked here: https://issues.chromium.org/issues/327024930

**Comment by captainbrosset** [comment]
@Svish if you're able, could you please take a look at the upstream issue linked in my previous comment? Google is trying to repro the problem, but is unable to. You might be able to provide extra information that would help them repro.
