### ISSUE TITLE
Detached elements node list is not populated when elements are fetched

### ISSUE THREAD

**Issue by TaranTwomey** [MicrosoftEdge/DevTools#233]
Recently I have been making great use of the 'Detached Elements' tool that Edge DevTools provides, however I noticed after a recent upgrade to the latest versions of Edge that it has stopped populating the Nodes list when collecting.

This issue appears to affect even the latest Canary, as well as the latest stable 122 version (122.0.2365.63) for 64-bit Windows 10. A coworker of mine who is also using the tool is still running 121.0.2277.128 and the tool appears to function correctly. I am currently unable to downgrade my version of edge, so I cannot test this precisly, but if I am able to downgrade, I will update this issue.

Reproduction:
1. Load the demo page from [microsoftedge.github.io/Demos/detached-elements/](https://microsoftedge.github.io/Demos/detached-elements/)
2. Following the same steps from the demo, generate traffic using the 'fast traffic' button.
**Generated Traffic, before tool is run**
![image](https://github.com/MicrosoftEdge/DevTools/assets/87681530/47872d5e-f0fc-450f-abed-b8acd74d749f)

3. Switch to room 2.
4. Run the detached elements tool by clicking 'get detached elements'.
**Switch Room, collect detached elements**
![image](https://github.com/MicrosoftEdge/DevTools/assets/87681530/bfc1fe35-3f04-42df-9617-39c5b1a38a4d)
_Note that the count in the top right of the tool has updated to show the number of detached elements, but the node list is not populated_

This issue appears to affect the latest Canary as well (124.0.2435.0 canary (64-bit)).

AB#49247073

**Comment by captainbrosset** [comment]
Thanks so much for reporting this, and providing these details. I had not yet updated my Stable Edge, so I was able to test with 121 and confirmed that it worked fine there.
After update, the tool no longer displays the detached nodes.
I also tested in Canary (124), where the feature also doesn't work anymore.

So you've discovered a 122 regression that, unfortunately, went through our release process undetected. I'll mark this up for the team to investigate quickly.

**Comment by DamonYu6** [comment]
Same issue with Version 122.0.2365.80 (Official build) (x86_64) MacOS. Any updates?

**Comment by captainbrosset** [comment]
No updates to share at this stage yet, but we're working on it.

**Comment by nyfer** [comment]
@captainbrosset  till then any alternative that we can try?

**Comment by captainbrosset** [comment]
You can also use the **Memory** tool and search for detached elements. 

1. Open the **Memory** tool.
2. Run your scenario of choice on the webpage.
3. In the tool, click **Take snapshot** to capture a heap snapshot.
4. In the snapshot, type **detached** in the **Class filter** text box at the top.

![image](https://github.com/MicrosoftEdge/DevTools/assets/1152698/fa5df41f-6346-413c-8bf1-efc7277e71ed)

Hope this helps.

**Comment by kheos31** [comment]
Hello, still no update on this issue?

Thanks in advance.

**Comment by captainbrosset** [comment]
No update to share yet on this. I'll get back to you all as soon as I hear more.

**Comment by j-saws** [comment]
this would also be helpful for us to have working again.

**Comment by Chrisyjs** [comment]
Hello, still no update on this issue?

**Comment by robpaveza** [comment]
Hi @TaranTwomey and @Chrisyjs - this issue has been fixed in Edge 126. We don't currently plan to back-port this into 124 or 125 given our current release schedule. Edge 126 is currently in Canary and Dev channels, which you can download here: https://www.microsoftedgeinsider.com/

Thanks!

**Comment by tomeronen** [comment]
@robpaveza this work for me after update! Love this tool thanks so much ❤️

**Comment by captainbrosset** [comment]
This is great, thank you for confirming that the feature is now working for you.
Closing the issue.

**Comment by alltabs** [comment]
Homie. Any update about my issue? Waiting for response. Thanks you

**Comment by alltabs** [comment]
﻿Homie. Any update about my issue? Waiting for response. Thanks you
