### ISSUE TITLE
how to disable the edge-json-viewer flag

### ISSUE THREAD

**Issue by youthlin** [MicrosoftEdge/DevTools#238]
In previous version, we can disable `edge-json-viewer` in `edge://flags/`.

But now( **`version: 123.0.2420.53 (正式版本) (x86_64)`**   ), I can not find this:
<img width="1201" alt="image" src="https://github.com/MicrosoftEdge/DevTools/assets/6056413/ab9cba23-5581-4aab-83c6-b2bd004844d4">

**Comment by youthlin** [comment]
https://github.com/MicrosoftEdge/DevTools/issues/87
https://github.com/zxlie/FeHelper/issues/312
https://github.com/tulios/json-viewer/issues/339

**Comment by captainbrosset** [comment]
Thanks for filing. I'll discuss with the team about this and we'll get back to this issue with an update.

**Comment by bafflingbug** [comment]
Is there any other way to disable JSON Viewer？ @captainbrosset 

----
It was a good idea, but now it's very bad. It will cause other third-party plug-ins to fail. Most of these experiences are better than the official ones. Hope there is a way to disable it.

**Comment by captainbrosset** [comment]
We're currently investigating why the flag is not visible anymore, and working on bringing it back.
I'll let you know when we have a fix ready. In the meantime, no, unfortunately, there is no way to disable the JSON Viewer.

**Comment by captainbrosset** [comment]
We have a fix almost ready, and are working on getting it deployed in Edge.

**Comment by jdoxx2** [comment]
Did they fix the problem? because that detail has just been presented to me

**Comment by captainbrosset** [comment]
No, the flag that's used to disable the built-in JSON viewer has not yet been restored in Edge. Still working on it. Thank you for your patience.

**Comment by BenClist-BC2** [comment]
Any update on this please? I've had to resort to using Chrome because of this, and I'd much rather be back using Edge.

**Comment by captainbrosset** [comment]
The flag that's used to disable the built-in JSON viewer will be available again in Edge starting with the next release (124), shipping on April 18.

**Comment by captainbrosset** [comment]
Closing this as fixed based on my latest comment. But if you still don't have the flag **and** you have verified that you have Edge 124+, then feel free to comment and I'll re-open the issue.

**Comment by MarvinXu** [comment]
@captainbrosset still no flag
![image](https://github.com/MicrosoftEdge/DevTools/assets/7382357/f00f6b3d-eb3d-45a5-9d38-7582dfc4efde)

**Comment by sanam-7** [comment]
@captainbrosset  - Still don't see the flag after updating to '124.0.2478.51'
<img width="1711" alt="image" src="https://github.com/MicrosoftEdge/DevTools/assets/3677346/e5f416d9-0439-4b87-b2b7-8cd4d8e5e2cd">

**Comment by BenClist-BC2** [comment]
> Closing this as fixed based on my latest comment. But if you still don't have the flag **and** you have verified that you have Edge 124+, then feel free to comment and I'll re-open the issue.

@captainbrosset still no sign of the flag in 124.0.2478.51

**Comment by captainbrosset** [comment]
Sorry for the inconvenience. Looking into this now ...

**Comment by jdoxx2** [comment]
without flag
![Captura de pantalla_22-4-2024_19716_flags](https://github.com/MicrosoftEdge/DevTools/assets/51023407/b493112e-7cb5-4a0b-842b-fbffd4cbe4e9)

**Comment by anomaly404** [comment]
Still not available :(

**Comment by atas** [comment]
The built-in JSON viewer suppresses the JSON Viewer extensions and stops them from working likes of https://github.com/callumlocke/json-formatter. The extensions have more capabilities than the built-in JSON Viewer e.g. expanding collapsing the JSON tree. Bringing the feature flag would be very helpful especially if the extensions cannot take higher precedence over the built-in viewer.

**Comment by captainbrosset** [comment]
Thank you. We are aware of the problem and of the fact that some people prefer using extensions instead. We're working on bringing the flag back for good.

**Comment by atas** [comment]
Thank you for working on it very quick and looking into it. I don't want to sound impatient but still want to ask out of planning purposes. Do we have an idea approximately when the remedy would be out? If planned for later, it might be better for developers to move their setup to another Chromium-based browser to not to affect the productivity while working with JSON APIs.

**Comment by captainbrosset** [comment]
I have some update on this. Thank you all for your patience, but it looks like I'll have to ask for even more patience.
While we did mean for the flag to be added again in Edge 124 (the current stable release), that didn't happen. I just confirmed that the flag is in Edge version 125 though:

![image](https://github.com/MicrosoftEdge/DevTools/assets/1152698/a181aafb-b92a-4e01-bf17-318243ef1707)

This next version is due to become stable on May 16th, 2024. So, in a little more than 2 weeks from now, the flag to disable the JSON Viewer will be available in Microsoft Edge again.

Apologies again for the inconvenience. But also, if there are features of other JSON viewers that you wished were in the Edge one, please do let us know by [creating a new issue on this repository](https://github.com/MicrosoftEdge/DevTools/issues/new?assignees=&labels=feature&projects=&template=feature.md).

**Comment by BenClist-BC2** [comment]
@captainbrosset thanks for the update. For our use case it's not that features are missing, it's that we use browser extensions to take JSON data and make it editable. One example of this allows administrators to make easy updates and fixes to records in Microsoft Dataverse on data that isn't necessarily displayed on the frontend.

Those extensions can't function when Edge hijacks the JSON rendering.

**Comment by captainbrosset** [comment]
@BenClist-BC2 thanks for the comment. I moved your request to a new issue, and asked a few questions about it there: https://github.com/MicrosoftEdge/DevTools/issues/251. Please take a look if you have some time. Thanks a lot!

**Comment by atas** [comment]
Will anyone adding some kind of json viewer/editor extension from the stores have to disable the flag to be able to use them? Is it a concern to divert more from the other Chromium-based browsers and to widen the differences gap? Just asking.

**Comment by ErnestDong** [comment]
> Will anyone adding some kind of json viewer/editor extension from the stores have to disable the flag to be able to use them? Is it a concern to divert more from the other Chromium-based browsers and to widen the differences gap? Just asking.

see [here](https://chromewebstore.google.com/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc?pli=1)

have been waiting sooooooooo long to get the flag back

**Comment by youthlin** [comment]
`edge://flags/#edge-json-viewer` is now available on version `125.0.2535.51`
<img width="785" alt="image" src="https://github.com/MicrosoftEdge/DevTools/assets/6056413/6bcae31a-1e6a-4e1f-a94a-bc9000c4ec3e">

**Comment by kdg2k2** [comment]
> I have some update on this. Thank you all for your patience, but it looks like I'll have to ask for even more patience. While we did mean for the flag to be added again in Edge 124 (the current stable release), that didn't happen. I just confirmed that the flag is in Edge version 125 though:
> 
> ![image](https://private-user-images.githubusercontent.com/1152698/326515919-a181aafb-b92a-4e01-bf17-318243ef1707.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjMzNjIsIm5iZiI6MTcyODQ2MzA2MiwicGF0aCI6Ii8xMTUyNjk4LzMyNjUxNTkxOS1hMTgxYWFmYi1iOTJhLTRlMDEtYmYxNy0zMTgyNDNlZjE3MDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDgzNzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg3OGEyM2QwYzZjMjI3NGFmYTAyZjRlYjljYzllZTEzZWUzM2Y5YzcxYjY5OTg1NDI4YWQyMGJhOGUzYTRiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iFWptJDFUVDJS-u5J9M16EHvFTXJlKiB8qFZHb7ywJo)
> 
> This next version is due to become stable on May 16th, 2024. So, in a little more than 2 weeks from now, the flag to disable the JSON Viewer will be available in Microsoft Edge again.
> 
> Apologies again for the inconvenience. But also, if there are features of other JSON viewers that you wished were in the Edge one, please do let us know by [creating a new issue on this repository](https://github.com/MicrosoftEdge/DevTools/issues/new?assignees=&labels=feature&projects=&template=feature.md).

god bless you! thanks a lot 🙆‍♂️

**Comment by waded** [comment]
Given this is a relatively findable ticket regarding enable/disabling Edge JSON Viewer, and the flag evidentially has disappeared and reappeared across versions before, can we get a brief update on current status? I noticed there is no such flag as of Edge 132 if not earlier versions - is that expected? (I think the answer is yes, because this feature has been completely removed - but would be good to confirm.)

**Comment by robuxlarp** [comment]
I'm literally unable to view any JSON files like before.

![Image](https://github.com/user-attachments/assets/1f0cc575-b717-469a-a7ba-b1c3d5818d08)

**Comment by leahmsft** [comment]
@waded yes, that's correct there's no flag for JSON Viewer anymore. JSON Viewer has been deprecated and removed from Microsoft Edge.
