### ISSUE TITLE
Copilot explain icon doesn't work

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftEdge/DevTools#239]
From @ltinirary in #203.

**In the sidebar setting page,I can't change the options. and I'm sure I'm logged in.**
![7e7fe8d2f2413eb920a9c904df3aa9d](https://github.com/MicrosoftEdge/DevTools/assets/79144923/e90bf156-0e8e-4ae8-9672-5e3fdbdf6305)

**I can see this copilot button on the console, but clicking on the button doesn't work.**

![image](https://github.com/MicrosoftEdge/DevTools/assets/79144923/3947889d-ad8b-44d4-90bb-85cfff559823)

_Originally posted by @ltinerary in https://github.com/MicrosoftEdge/DevTools/issues/203#issuecomment-2017527881_
            

AB#49639728

**Comment by captainbrosset** [comment]
@ltinirary: this is actually by design. See https://learn.microsoft.com/en-us/copilot/faq which explains that Microsoft Copilot is not availablein all countries.

**Comment by ltinerary** [comment]
😳Well, hopefully someday in the future it can be supported in china.

**Comment by captainbrosset** [comment]
Yes, I hope that too.
In the meantime, we'll make sure the icons are not shown in countries/regions where Copilot is not supported.
