### ISSUE TITLE
View payload data for POST requests in the network tab (to view uploaded files)

### ISSUE THREAD

**Issue by richardsondev** [MicrosoftEdge/DevTools#24]
When uploading a file via a POST request created by a form with content type "multipart/form-data", all form data disappears from the request in the network tab.

There was a similar report for Chrome as well here: https://stackoverflow.com/a/59871612

Expected:
Show the form data in the network tab for these types of POST requests. Ideally, if all the data including the file data could be shown, it would be great. Although, just having the non-file data would be nice too.  

To reproduce:
1. Go to a browser page with a form file upload like: https://www.filestack.com/fileschool/html/html-file-upload-tutorial-example/
2. Open the network tab and ensure recording is on
3. Upload a file via the form and submit
4. Inspect the POST request in the network tab and see there is no form data visible

AB#38549603

**Comment by captainbrosset** [comment]
Thanks for filing this issue. It'd be really good if we could see the payload data indeed. I noticed that Firefox DevTools does have it. Here is an example:

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/1152698/158563050-545b3ef0-0912-4600-97e8-ce49c25b101e.png">

The **Request** sidebar tab in the **Network** panel shows all of the data sent with the form submission, including the file content.

If I do a `GET` request with Chrome or Edge, I also get something similar:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/1152698/158563340-6f283de5-ce75-4a82-ab73-9314360242e1.png">

Unfortunately, I'm not seeing the **Payload** sidebar tab for `POST` requests. So this seems like a good thing to add.

**Comment by captainbrosset** [comment]
I've moved this to the team's internal backlog for evaluation and prioritization. Thanks for your feedback!

**Comment by GoldenretriverYT** [comment]
any chance this will be implemented?

**Comment by captainbrosset** [comment]
Testing again today with the steps provided in this issue's description, and things seem to have changed.
I now see a **FormData** section under **Payload**, which shows the file that has been sent:

![image](https://github.com/MicrosoftEdge/DevTools/assets/1152698/d14a5ce7-1252-42e8-a9a2-7e9b3a02247f)

@richardsondev mind testing again and letting us know what you see?

**Comment by richardsondev** [comment]
Tested with 125.0.2535.92 and it looks good to me! Thanks for the resolution

**Comment by captainbrosset** [comment]
Great to hear. Closing this issue.

**Comment by blama** [comment]
Hi @captainbrosset,

I noticed a similar thing and found this thread. I can also see data under payload, but it seems that the size of the file uploaded is not included in the list of requests:
![grafik](https://github.com/user-attachments/assets/072d3d9d-6df0-431f-bf6e-491cff6dff8d)
As you can see from the time it took, this is the upload request (here ~5MB), but it shows only 863 Byte as request size.

Could you include this size in the table as well?

**Comment by captainbrosset** [comment]
@blama sorry about the delay replying here. Would you please open a new issue to track you specific request? Also, if you can, please provide the URL of a site where we can easily reproduce what you're seeing. I'd like to make sure I understand the request correctly, and I feel like a new, dedicated, issue would be better for this.
Thank you.
