### ISSUE TITLE
Can't export PDF file in both Portrait and Landscape at the same time? 

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/DevTools#240]
* I'm having trouble exporting PDF files in Microsoft Edge. I can't export it both landscape and portrait in the same document. I do the same on Google Chrome and everything works normally.
* I have set in CSS before printing the document, here is the code:

<pre>
.page1 {
       page: landscape-page;
}

.page2 {
       page: portrait-page;
}

@page landscape-page {
       size: A4 landscape;
}

@page portrait-page {
       size: A4 portrait;
}
</pre>

**Comment by captainbrosset** [comment]
This repository is specific to DevTools. DevTools is a developer feature in Edge which is not related to PDF, export, or print CSS handling.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
