### ISSUE TITLE
Chromium bug

### ISSUE THREAD

**Issue by Dbitome88** [MicrosoftEdge/DevTools#241]
Several weeks ago. I downloaded a fake Firefox browser and it can a bug on Windows 11. I installed Windows 10 to see if things would get better but it didn't. The Edge browser is still giving me problems. I checked the console and full of errors and warning. There was a small icon on right side of the URL that keeps appearing when I used my email. I think it's a filter to stop me from downloading.
Other issues include: Corrupted Printer, Profile, Email, JavaScript, Console, Favorites, Screenshot.  My Proton mail was altered as soon as installed Windows 10 and I don't how to repair it,  
![Capture PNG Deck](https://github.com/MicrosoftEdge/DevTools/assets/122765248/347de446-f534-4319-9b12-8b8d8aadc6e3)

**Comment by captainbrosset** [comment]
Sorry that you're facing issues. However this particular problem does not seem like an Edge DevTools issue. The fact that DevTools shows errors and warnings has nothing to do with your computer potentially malfunctioning. DevTools only shows errors and warnings that a webpage generate at runtime.
Closing this as out of scope for this repository. But feel free to open an issue by using the Feedback Hub app on Windows. Thanks for your understanding.
