### ISSUE TITLE
how to modify devtools UI font?

### ISSUE THREAD

**Issue by Wangxin666888** [MicrosoftEdge/DevTools#244]
As the picture show
![20240406125103](https://github.com/MicrosoftEdge/DevTools/assets/142091421/41a9d11a-9ae6-4a1c-a256-c6643d1966b9)

I use devtools in microsoft webview2 control in my wpf app.

how can I modify the font family to Consolas?

Thanks!

AB#50060456

**Comment by captainbrosset** [comment]
Thanks for reaching out. I'm not sure there's a way to change the font that's used in DevTools. It looks to me like DevTools is using the font that's normally used to render Chinese characters, except that here, everything is displayed in in English. And it's weird that the tabs don't use the same font.

**Comment by Wangxin666888** [comment]
> Thanks for reaching out. I'm not sure there's a way to change the font that's used in DevTools. It looks to me like DevTools is using the font that's normally used to render Chinese characters, except that here, everything is displayed in in English. And it's weird that the tabs don't use the same font.

It seems that the font used here is according to the version of WebView2 Runtime.

Above pic. was shown in version 123.0.2420.81.

But when I back to version 122.0.2365.92, all is shown as my expected.
![20240409171936](https://github.com/MicrosoftEdge/DevTools/assets/142091421/bc7fc38a-6791-4524-8f9a-9b62e363548d)

**Comment by captainbrosset** [comment]
Thank you for the additional investigation details.
