### ISSUE TITLE
New JSON Viewer is changing the JSON serialized value for some numbers

### ISSUE THREAD

**Issue by shawnwildermuth** [MicrosoftEdge/DevTools#246]
When using Edge for testing of an API, the JSON Viewer is changing the underlying JSON. See below:

![image](https://github.com/MicrosoftEdge/DevTools/assets/568272/0ef94bac-2ac7-4dca-80f8-5b8f7aa1ddf9)

I'd prefer to just turn off the view for now (since I am using extensions that do this, but they aren't enabled when the JSON Viewer is on).

**Comment by captainbrosset** [comment]
Thanks for filing this issue. I'm having some difficulties reproducing the problem though. Here is what I tried:

1. Open a new tab in Microsoft Edge.
2. Enter the following URL in the address bar: `data:text/json,[{"id": 1636, "price": 43.00}]`.
3. Press Enter.

Here is the result:

![image](https://github.com/MicrosoftEdge/DevTools/assets/1152698/b7c3ee91-c2ff-48c1-acf3-d0960d753eca)

I'm not seeing the change to `{value: "43.00n", "type": "Big Number"}` like you do.

@shawnwildermuth would you be able to provide a URL or JSON file for us to reproduce the issue?
Also, what's your Edge version?

In terms of disabling the JSON Viewer, you can do so by following these steps:

1. Open a new tab and go to `edge://flags`
2. In the search box at the top of the flags page, search for **json viewer**
3. Change the flag to **Disabled** and then restart Edge.

![image](https://github.com/MicrosoftEdge/DevTools/assets/1152698/3aa47bdb-89d7-413b-a0ec-2a744cee8bb0)

**Comment by shawnwildermuth** [comment]
So, I am seeing the same thing you are (because the JSON Viewer isn't being enabled for this query:

![image](https://github.com/MicrosoftEdge/DevTools/assets/568272/39e68076-5afd-471d-99f3-d3a36441ee38)

But when I go to an URL (instead of a data block or even a local file), the JSON Viewer is used:

![image](https://github.com/MicrosoftEdge/DevTools/assets/568272/2e694dc7-1216-46aa-a4fb-6fa3207b220f)

When I open the edge://flags, I don't see a JSON Viewer. 

![image](https://github.com/MicrosoftEdge/DevTools/assets/568272/4a0200a5-8c46-4a02-923a-6558b4b4c7e6)

I seem to have the latest version (though I am not using a preview of Windows):

![image](https://github.com/MicrosoftEdge/DevTools/assets/568272/48a8871d-9c67-49ee-852b-84d4cbcbb19f)

**Comment by captainbrosset** [comment]
On this screenshot:

![image](https://github.com/MicrosoftEdge/DevTools/assets/1152698/d24f72ad-345f-4413-9e8d-a486635c702c)

the toolbar which you point to doesn't belong to the official Microsoft Edge JSON viewer. I don't know where it comes from, but it isn't our JSON viewer. Do you have an extension installed that handles JSON responses? I'm wondering if the Edge JSON viewer and a potential extension are competing to display JSON responses.

**Comment by shawnwildermuth** [comment]
I didn't think so. Let me look. That would explain a lot.

**Comment by shawnwildermuth** [comment]
So sorry for wasting your time. This was JSON Beatify extension that I thought I disabled. I mistakenly thought the icon here disabled, not just hid from the tool bar:

![image](https://github.com/MicrosoftEdge/DevTools/assets/568272/7fbaf80c-7a2f-4efa-a2e6-428a447ba4d0)


Totally a problem between the chair and the keyboard.

**Comment by captainbrosset** [comment]
Thanks for checking and reporting.
