### ISSUE TITLE
[Request feature] Json viewer

### ISSUE THREAD

**Issue by chungxon** [MicrosoftEdge/DevTools#250]
Hi Team and @captainbrosset,

I'm reaching out from the [comment](https://github.com/MicrosoftEdge/DevTools/issues/238#issuecomment-2083186844)

I have been using an extension called JSON Formatter ([Edge](https://microsoftedge.microsoft.com/addons/detail/json-formatter-for-edge/njpoigijhgbionbfdbaopheedbpdoddi), [Chrome](https://chromewebstore.google.com/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en&pli=1)) to view and interact with JSON content in the browser effectively

So I wish you could add these features to Edge JSON viewer

- [ ] Tree is collapsible by default
- [ ] Clickable URLs
- [ ] Show the total number of children of a key if the value is a list or another json

Thank you for your time and attention.

Regards,
Son.

AB#50460235

**Comment by captainbrosset** [comment]
Thank you Son. These sound like great feature ideas. Adding this to our team's backlog for evaluation and prioritization.

**Comment by dshubhadeep** [comment]
@captainbrosset Adding to these, allowing the json to be accessible in the browser console through a global variable would also be extremely helpful.

**Comment by BieleckiLtd** [comment]
Is there a way in MS Edge to set a preference for the type of content I prefer? By default, it sends text/html, application/xhtml+xml, application/xml;[...] in the Accept request header. If an API has multiple formatters implemented, it will prioritise the response format in XML over JSON.

**Comment by leahmsft** [comment]
Closing since JSON Viewer has been deprecated and removed from Microsoft Edge.
