### ISSUE TITLE
[JSON viewer] Make JSON data editable

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftEdge/DevTools#251]
From @BenClist-BC2  in https://github.com/MicrosoftEdge/DevTools/issues/238#issuecomment-2083635047:

> we use browser extensions to take JSON data and make it editable. One example of this allows administrators to make easy updates and fixes to records in Microsoft Dataverse on data that isn't necessarily displayed on the frontend.

AB#50579917

**Comment by captainbrosset** [comment]
@BenClist-BC2 Can you explain how you make the data editable exactly? Does the extension you use have a way to save the data back to disk? Which extension is it?

**Comment by BenClist-BC2** [comment]
@captainbrosset It's writing back to Dataverse directly, it's not something you want to build into Edge. There's a public example that uses the same approach here https://chromewebstore.google.com/detail/prettifymywebapi-for-micr/pcgbnpkpijlcjeleijaaahlonafdlfno

**Comment by captainbrosset** [comment]
Oh ok, got it. So this is different from what I thought this issue was about. Let's keep this issue to track making the built-in JSON viewer able to edit JSON responses or files though.

**Comment by leahmsft** [comment]
Closing since JSON Viewer has been deprecated and removed from Microsoft Edge.
