### ISSUE TITLE
Sticky favorites and sticky pinned tabs that show in all workspaces

### ISSUE THREAD

**Issue by bellysavalas** [MicrosoftEdge/DevTools#252]
Hi, 

I am using the Edge Workspaces, which is a really great feature. The only thing that is slightly annoying is that I have to add favorites to each workspace. I can see why you did it like that -- so that each workspace can be clean, with only info relevant to that workspace. However, some favorites are pertinent across workspaces, as are some tabs.

Would it be possible for you to consider two new features?

1) Sticky Favorites -- These would be favorites that the user has selected to be added to the toolbar of all workspaces.
2) Sticky Tabs -- These would be pinned tabs that are pinned to all workspaces.

Thanks for a great product, and for your consideration of my request.

**Comment by captainbrosset** [comment]
Thank you for the nice words, and for raising this feature request. Unfortunately, you've come to the wrong place. This repo is dedicated to feedback about Edge DevTools. DevTools is a series of web development tools for people who build websites.

Could you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.

**Comment by bellysavalas** [comment]
Thank you for your response. I will report using your instructions.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
