### ISSUE TITLE
Error playing TIKTOK videos

### ISSUE THREAD

**Issue by samparbec** [MicrosoftEdge/DevTools#253]
Hello, I have detected a problem when playing videos from the TIKTOK platform from the browser on Android, and is that since version 97.0.1072.78 are no longer played, ie, before if everything worked but in the new versions you have touched something in the code that no longer play.

Attached is a video showing that in the previous version it plays and in the new one it does not.

https://github.com/MicrosoftEdge/DevTools/assets/86065304/6424cf0d-afaf-4b79-bea1-e6c6f66cfbea

**Comment by captainbrosset** [comment]
Thanks for reaching out and sorry about the issue you're facing. However, this repository is specific to DevTools. DevTools is a developer feature in Edge which has nothing to do the Edge app for Android, or with playing videos.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

On Desktop: 

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

On Mobile:

1. Tap the hamburger menu icon at the bottom-right corner.
2. Swipe right to display the second page of options.
3. Tap **Help and feedback**.

Thank you for your understanding.
