### ISSUE TITLE
新标签页出现错误弹窗

### ISSUE THREAD

**Issue by lyn1022** [MicrosoftEdge/DevTools#258]
没当打开新标签页就出现undefined的提示
![屏幕截图 2024-05-21 170919](https://github.com/MicrosoftEdge/DevTools/assets/170411986/55574817-1c21-4376-9ab0-4e55c73a4f0c)
![屏幕截图 2024-05-21 171002](https://github.com/MicrosoftEdge/DevTools/assets/170411986/f48b8cda-c1b4-48b2-9a23-96c9ec8df4da)
![屏幕截图 2024-05-21 171018](https://github.com/MicrosoftEdge/DevTools/assets/170411986/fa4b0f08-3f97-4670-b0ce-1ae080baaff4)
![屏幕截图 2024-05-21 171046](https://github.com/MicrosoftEdge/DevTools/assets/170411986/c36afb43-8f57-4716-98c3-6c98998ba3ae)

**Comment by captainbrosset** [comment]
Thanks for reporting this. However, it seems like this is related to the browser itself, not to DevTools (which this repository is about).
DevTools is a developer feature in Edge which has nothing to do with opening new tabs.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
