### ISSUE TITLE
Windows Notification Service endpoints for Web Push are down

### ISSUE THREAD

**Issue by collimarco** [MicrosoftEdge/DevTools#262]
Please note that today the endpoints (`*.notify.windows.com`) used for web push are completely down.

For example:

```
Failed to open TCP connection to wns2-ln2p.notify.windows.com:443 (execution expired)
```

Please forward this to the appropriate team and fix it.

**Comment by captainbrosset** [comment]
The Windows Push Notification Services (WNS) has an article documenting how to report issues: https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/troubleshoot-notifications#reporting-an-issue

This repository here is specific to Microsoft Edge DevTools, which is a different product. I suggest reaching out to the right team directly through their feedback channels instead.

Thanks for your understanding.
