### ISSUE TITLE
"Edit and Resend" feature is not working in v127.0.2651.86

### ISSUE THREAD

**Issue by Bricks-Man** [MicrosoftEdge/DevTools#268]
This issue like #224 

When I use Edit and Resend in devtools, it's response a 404!!!
![image](https://github.com/user-attachments/assets/24a485e4-5387-4e40-b3ca-6439488bbc84)

AB#53968311

**Comment by captainbrosset** [comment]
I just tested with Edge 127, but could not reproduce the issue, the tool works fine for me. Is this still happening for you? If so, can you provide more information that could help us reproduce and fix the issue please? Does this always happen, or only sometimes? Does it only happen on a given website, or any site? What's your operating system? Any little detail you can think of would help us. Thank you.

**Comment by LRHF** [comment]
Same here:
Version 128.0.2739.79 (Official build) (64-bit)

![image](https://github.com/user-attachments/assets/903fcb89-eb91-4a93-883b-c73ff9f0a027)

**Comment by captainbrosset** [comment]
Ok, I was finally able to reproduce the issue just now. I will make sure this is on our backlog.

**Comment by LRHF** [comment]
I installed the Canary version and "Copy and Resend" is working fine.

I remember I had a similar issue some months ago and had to reset Edge, apparently the issue has something to do with the Profiles, when you setup the Work and Personal profiles somehow that affects the "Copy and Resend" feature, but that is just a hypothesis.

**Comment by Victor-Chow** [comment]
I also encountered this problem, after the upgrade to the latest version can work, but now the latest version doesn't work either

**Comment by Sublime1** [comment]
Can confirm - I am also getting this issue on 128.0.2739.79. I don't use Profiles. 
It happens on multiple sites. Happens with both GETs and POSTs.
I had a feeling but no evidence that it might be related to SSL certs.

Edition	Windows 11 Pro
Version	23H2
Installed on	‎26/‎07/‎2023
OS build	22631.4169
Experience	Windows Feature Experience Pack 1000.22700.1034.0

**Comment by captainbrosset** [comment]
This is under investigation by our team. Sorry about that, and thank you for your patience.

**Comment by arnesacnussem** [comment]
edge version 128.0.2739.79
when opening that tab or devtool, it try to load following URL
https://devtools.azureedge.net/serve_file/@9fa544bdb74fe73e617bb893be219c25d65ef2e3/third_party/network-console/dist/index.html

**Comment by RemMai** [comment]
On September 27, 2024, the version of Edge browser was 129.0.2792.65, and this issue has been fixed. I can now use this feature.
Thank you, hardworking development experts.❤

**Comment by LRHF** [comment]
Awesome, I updated the browser and can confirm this is now working fine. Thank you so much!!!

**Comment by Victor-Chow** [comment]
> This is under investigation by our team. Sorry about that, and thank you for your patience.

@captainbrosset So what's the cause of the problem?

**Comment by Victor-Chow** [comment]
@captainbrosset Now it works, but when you set Referer in headers, you don't see Referer in the request header.

**Comment by leahmsft** [comment]
@Victor-Chow Thanks for reporting that bug. I opened a new issue for it here: https://github.com/MicrosoftEdge/DevTools/issues/279

Can you please help by providing more details like the environment (OS, browser version), repro steps, and any other additional details for our engineering team in the new issue I created?

**Comment by lankenau-dp** [comment]
Microsoft Edge Version 133.0.3065.69 (Official build) (64-bit):
When I use "Edit and Resend" in devtools, it still responds with a HTTP 404 (see screenshot). We are behind a firewalls that allows no outgoing connections to the internet. When outgoing connections are allowed, the issue disappears.

![Image](https://github.com/user-attachments/assets/e176560c-db16-4219-b5f5-7bc50f8c61b4)

**Comment by oyar99** [comment]
I am seeing this issue on Version 135.0.3179.54 (Official build) (64-bit).

![Image](https://github.com/user-attachments/assets/73afdc29-55be-4169-8d2c-1d6d614aa591)

**Comment by lihaishi** [comment]
I am seeing this issue on Version 135.0.3179.54 (Official build) (64-bit).
![Image](https://github.com/user-attachments/assets/ca8fb9a1-decd-48be-90e2-d8c9e4263153)

**Comment by kingjotaro** [comment]
Same here, broken again on last update

**Comment by Sasurtio** [comment]
Broken again for me too

Version 135.0.3179.54 (Official build) (64-bit)
![Image](https://github.com/user-attachments/assets/5936783d-f639-415e-b36a-6010084a97a5)

**Comment by leahmsft** [comment]
Hi everyone, the fix will be in next week's Stable update. In the meantime, please use DevTools in the Dev or Beta channels.

**Comment by abatishchev** [comment]
+1. It's May now and it still doesn't work as of version **136.0.3240.92**

![Image](https://github.com/user-attachments/assets/df892f8c-28e0-4a10-802a-766704060984)

**Comment by up9t** [comment]
Still don't work

![Image](https://github.com/user-attachments/assets/b6680b37-1e03-41a2-a539-ae9e3d347b04)

**Comment by abatishchev** [comment]
It was fixed in v137

**Comment by Sunwuyuan** [comment]
Reproduced in version 139.0.3405.36

**Comment by Flamesh90** [comment]
This is probably related to internet/ external network blocked machines. 

My server has an endpoint i am trying to test which is open for internal traffic only. (blocked for external traffic - internet)
and i get a 404.

On my other server which is open to traffic there is no issue.

is this a feature that relies on external resources to be loaded?

**Comment by Sunwuyuan** [comment]
<img width="2503" height="1378" alt="Image" src="https://github.com/user-attachments/assets/bfd7c4d7-467f-49c8-b735-c4fd54b08e44" />

**Comment by kingjotaro** [comment]
Down again?

**Comment by PowershellKnut** [comment]
> Down again?

I have the same problem now! Edge version 140.0.3485.66

**Comment by Fusion-Priyakant** [comment]
Same issue with Version 140.0.3485.81 (Official build) (64-bit)

**Comment by JacquesRamsdenGit** [comment]
Version 140.0.3485.81 (Official build) (64-bit)

Confirmed broken also from my side. 
Just loads a blank screen

**Comment by PowershellKnut** [comment]
Also broken i Dev (142.0.3568.0), but seems to be working in the newest Canary build 142.0.3588.0
EDIT: I loads... But still broken. I get compiler error when trying to resend and whe whole developer tool page "freezes" and doesn't load any more requests. Cannot even close it. I need to open a new tab to be able to continue browsing.

**Comment by Curtis-Koenig-Gen** [comment]
Broken in Version 145.0.3800.70 (Official build) (arm64)

**Comment by andgdk** [comment]
Broken in Version 147.0.3912.72 (Official build) (64-bit)

**Comment by JoshuaHintze** [comment]
Broken in Version 148.0.3967.70 (Official build) (arm64)

**Comment by andgdk** [comment]
Working in Version 148.0.3967.83 (Official build) (64-bit) ^_____^
