### ISSUE TITLE
Where is the Microsoft repo/docs for building Edge's devtools-frontend?

### ISSUE THREAD

**Issue by june07** [MicrosoftEdge/DevTools#269]
Google's (for Chrome) is easy to find, and the docs are here: https://chromium.googlesource.com/devtools/devtools-frontend/+/main/docs/get_the_code.md

As well is there a hosted endpoint for the build as there is for Google's here: [chrome-devtools-frontend.appspot.com](https://chrome-devtools-frontend.appspot.com/)

**Comment by captainbrosset** [comment]
Edge DevTools is based on the open-source Chromium project, but isn't, itself, an open-source project.
Please let us know if you have questions about anything that's specific to Edge, and not in Chromium.

**Comment by june07** [comment]
Thanks for the info @captainbrosset . A shame Edge DevTools isn't open source but I guess it's totally within the license to be as such. Wonder if you can speak to the reason Microsoft chose to keep that part closed?

**Comment by captainbrosset** [comment]
Note that the vast majority of Edge DevTools is just like Chromium. The Edge team does provide some additional tools and features that are unique to Edge (and therefore closed source), but for the vast majority, what you see is Chromium, and our team does contribute a large amount of work "upstream", in Chromium directly.
