### ISSUE TITLE
Edge is very buggy with Intel Iris Xe

### ISSUE THREAD

**Issue by lucellent** [MicrosoftEdge/DevTools#270]
Context: 4K display, 13900H, 64GB Ram, RTX 3500 Ada, Vapor Chamber cooling, 2TB SDD + 1 TB SSD
 
YouTube on Edge is almost unusable for me. All videos have 1-2 second frame freeze (I don't know how else to explain it) every 10 seconds or so. This ONLY happens on Edge. Chrome works perfectly.
 
What I've tried so far:
-clean reinstall Windows 11 (multiple times)
-reinstall drivers
-install old/newest drivers
-disable extensions
-Task Manager is showing no signs of issues
-disable any energy efficiency features in Edge
 
From what I've read, it's an incompatibility issue with my iGPUs and Edge. The issue doesn't happen on Chrome. The only temporary fix I've found is changing ANGLE graphics backend to OpenGL. (UPDATE: This seems to have stopped working and the issue is full time here again.)
 
But even then, the issue still happens from time to time. This also isn't limited to videos, when I'm scrolling on websites, occasionally every 10 seconds or so when I scroll, there would be like 0.5 second lag/jump/freeze etc, just like whenever I'm watching a video.

**Comment by captainbrosset** [comment]
Sorry that you're experiencing this issue. However, this repository is specific to DevTools. DevTools is a developer feature in Edge which has nothing to do with how fast Edge plays videos.

Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
