### ISSUE TITLE
Video is not playing on android edge when passing video src as a blob

### ISSUE THREAD

**Issue by fahd313** [MicrosoftEdge/DevTools#272]
I want to play using html5 video player but video is not playing when passing video source as a blob source. Please find the JSfiddle url for reference.

https://jsfiddle.net/h12kmvdq/

**Comment by captainbrosset** [comment]
Thanks for filing this issue, however this repository is specific to DevTools. DevTools is a developer feature in Edge which has nothing to do with how videos get played in the browser.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
