### ISSUE TITLE
Copolit & sidebar not working on linux

### ISSUE THREAD

**Issue by amdkholil** [MicrosoftEdge/DevTools#278]
**Describe the bug**
The sidebar and its part copilot don't work. The copilot button is unclickable. In general, it should be related problems.

**Tested Distros**
- Linux mint 22
- NixOs
- Fedora
- Arch Linux
- see https://github.com/NixOS/nixpkgs/issues/345125

**Steps To Reproduce**
- Download Microsoft Edge Linux version from web (I choose .deb)
- Install Microsoft Edge
- Run Edge

**Expected behavior**
When I run edge I want to get to the right panel and copilot access.

**Screenshot**
![image](https://github.com/user-attachments/assets/dff670e1-e5a0-4e0f-96c3-14d19899d48d)

**Comment by leahmsft** [comment]
Thank you for filing. This bug isn't related to DevTools so it will be closed. 

Please report this bug by clicking Settings and more (...) > Help and Feedback > Send Feedback to get this bug to the right team.

**Comment by istvan-ujjmeszaros** [comment]
If sending a feedback would work in the Linux version of Edge :sweat_smile:
It would be great if you could forward this bug to the right team. Fortunately, Copilot is working via the https://copilot.microsoft.com/ URL.

**Comment by istvan-ujjmeszaros** [comment]
FYI, copying the `HubApps` file from my Windows installation to Linux seems to have solved it. That file was missing on Linux.

Location on Windows:
`Users\<username>\AppData\Local\Microsoft\Edge\User Data\Default`
Location on Ubuntu:
`~/.config/microsoft-edge/Default`

**Comment by RPDJF** [comment]
I mean, it's 2025 and it's still not resolved
Come on

**Comment by Zujaj** [comment]
This is totally insane! I've freshly installed Ubuntu LTS by erasing my Windows 11? How can I restore the `HubApps` ? Would taking the the `HubApps` from a fresh Windows make it work since I've already synced up my data on Ubuntu Edge?

**Comment by RPDJF** [comment]
> This is totally insane! I've freshly installed Ubuntu LTS by erasing my Windows 11? How can I restore the `HubApps` ? Would taking the the `HubApps` from a fresh Windows make it work since I've already synced up my data on Ubuntu Edge?

You can take mine from https://github.com/RPDJF/dotfiles/tree/master/.myconfig%2Fressources

**Comment by istvan-ujjmeszaros** [comment]
Please note that you may need to remove the `.txt` extension after downloading the file from GitHub. FYI I have compared this file from @RPDJF with the one on my PC and they are basically the same, mine is just one minor version newer. So, it seems to be safe to use this shared file.

**Comment by Zujaj** [comment]
@RPDJF and @istvan-ujjmeszaros thanks for your support. It worked perfectly! Hope the Microsoft team resolves this bug in a later Edge release for Ubuntu

**Comment by AN-SWAPNIL** [comment]
```Please note that you may need to remove the .txt extension after downloading the file from GitHub. FYI I have compared this file from @RPDJF with the one on my PC and they are basically the same, mine is just one minor version newer. So, it seems to be safe to use this shared file.``` This worked for my ubuntu 24.04. Btw  I didn't find any HubApps in my windows.

Thanks a lot @istvan-ujjmeszaros and @RPDJF.

**Comment by AN-SWAPNIL** [comment]
> Please note that you may need to remove the `.txt` extension after downloading the file from GitHub. FYI I have compared this file from [@RPDJF](https://github.com/RPDJF) with the one on my PC and they are basically the same, mine is just one minor version newer. So, it seems to be safe to use this shared file. 

This worked for my ubuntu 24.04. Btw I didn't find any HubApps file in my windows.

Thanks a lot @istvan-ujjmeszaros and @RPDJF.

**Comment by RPDJF** [comment]
It's nuts that it still isn't resolved

**Comment by DhananjayPorwal** [comment]
Thank you @RPDJF for providing the `HubApps` file. It’s functioning exactly as needed.

**Comment by ltade** [comment]
@RPDJF thank you so much man

**Comment by zerocoolroot** [comment]
> > This is totally insane! I've freshly installed Ubuntu LTS by erasing my Windows 11? How can I restore the `HubApps` ? Would taking the the `HubApps` from a fresh Windows make it work since I've already synced up my data on Ubuntu Edge?
> 
> You can take mine from https://github.com/RPDJF/dotfiles/tree/master/.myconfig%2Fressources

Hi,

I have Edge installed via Flatpak in Ubuntu 24.04 LTS.

I downloaded the **HubApps.txt** file, renamed it to just **HubApps**, and placed it in the following path:
/home/USER/.var/app/com.microsoft.Edge/config/microsoft-edge/Default

The Copilot icon remains in the upper right corner.

**Comment by sud0xenn** [comment]
> FYI, copying the `HubApps` file from my Windows installation to Linux seems to have solved it. That file was missing on Linux.
> 
> Location on Windows: `Users\<username>\AppData\Local\Microsoft\Edge\User Data\Default` Location on Ubuntu: `~/.config/microsoft-edge/Default`

Thanks for sharing this solution, it also helped me hide the copilot icon on the toolbar from settings now that the option is visible again.

Do you know if there's any other such file to enable Mouse Gestures? On Linux Mint, using right click just triggers the context menu instead of initiating whatever gesture.

**Comment by ahousley** [comment]
Just chiming in from the year 2025, where Copilot still needs a donor lung from Windows to breathe on Linux. I’m running Edge Version 140.0.3485.81 on Debian 13 (Trixie) with Gnome 48, and yep—still had to manually transplant the `HubApps` file from a Windows machine to get the sidebar working.

It’s wild that this issue was opened back in October 2024 and we’re still duct-taping Copilot together like some kind of penguin-powered Frankenstein. 🐧⚡

Microsoft folks, if you're listening: we love Copilot. We just want it to work without needing cross-platform organ donation. Please give Linux the love it deserves.

Filed by: a Copilot who’s alive thanks to a borrowed Windows lung and sheer stubbornness.

**Comment by sud0xenn** [comment]
> Microsoft folks, if you're listening: we love Copilot. We just want it to work without needing cross-platform organ donation. Please give Linux the love it deserves.

What's funny is people who hate copilot also had to perform a transplant lol. The option to disable copilot is absent until you get the hubs file

**Comment by whoisyurii** [comment]
October 2025, Linux Mint Cinnamon 22.2, still no fixes from Microsoft guys to it.

upd: 
> > This is totally insane! I've freshly installed Ubuntu LTS by erasing my Windows 11? How can I restore the `HubApps` ? Would taking the the `HubApps` from a fresh Windows make it work since I've already synced up my data on Ubuntu Edge?
> 
> You can take mine from https://github.com/RPDJF/dotfiles/tree/master/.myconfig%2Fressources

The solution from @RPDJF worked, thanks!

**Comment by ulisses15** [comment]
Notes from my attempt to fix:

- I downloaded the hubapps.txt file and placed it in the default folder and removed the .txt from the file name before placing it in the default folder
- The setting for the copilot button opened and I was able to remove the copilot button using the toggle in Appearance/Copilot and sidebar/Copilot
- I have multiple profiles and this only applied to my default profile.
- The steps have to be repeated for each profile. 
- in _/home/user/.var/app/com.microsoft.Edge/config/microsoft-edge_ there are folders labeled _profile 1, profile 2, etc._ 
- The HubApps file with .txt removed beforehand was placed in each profile folder
- The setting for the copilot button opened in each profile and I was able to remove the copilot button using the toggle in Appearance/Copilot and sidebar/Copilot

**Comment by CodeCatalyst-Foss** [comment]
> FYI, copying the `HubApps` file from my Windows installation to Linux seems to have solved it. That file was missing on Linux.
> 
> Location on Windows: `Users\<username>\AppData\Local\Microsoft\Edge\User Data\Default` Location on Ubuntu: `~/.config/microsoft-edge/Default`

Thanks my man, it worked like a charm. Utterly insane this STILL hasn't been fixed.

**Comment by fkoemep** [comment]
Just an FYI, this file seems to depend on the language of the browser/OS, I tried @RPDJF's HubApps file but it didn't work since my browser is not in english so I just had to resort to copying the file from my other device and then it finally worked without issues

Not related, but does anyone have an issue when downloading any file and choosing "Save As" in the dialog? Whenever I do that, the browser completely crashes so I always have to click on "Save"

**Comment by hernansr** [comment]
Same issue in Fedora installing through the official rpm
