### ISSUE TITLE
When you set Referer in headers, you don't see Referer in the request header in Network Console

### ISSUE THREAD

**Issue by leahmsft** [MicrosoftEdge/DevTools#279]
@captainbrosset Now it works, but when you set Referer in headers, you don't see Referer in the request header.

_Originally posted by @Victor-Chow in https://github.com/MicrosoftEdge/DevTools/issues/268#issuecomment-2404270160_
            

AB#54403378

**Comment by Victor-Chow** [comment]
Windows 11 22631.4037
Edge 129.0.2792.79
![image](https://github.com/user-attachments/assets/20463730-8b88-4ba9-a5ae-c99ab8582135)
![image](https://github.com/user-attachments/assets/4a8037bf-d5fe-4bb5-9d3d-b25fd880a566)

The first image is the original request, the second image is request by "Edit and Resend", obviously no referer.

**Comment by leahmsft** [comment]
@vidorteg to help take a look

**Comment by robpaveza** [comment]
Network Console in Edge DevTools works by issuing a `fetch` request on behalf of the page being inspected. As a result of this, it is not possible to set the `Referer` header, because that header is not respected [as per the `fetch` spec](https://fetch.spec.whatwg.org/#forbidden-request-header).
