### ISSUE TITLE
Custom snippets support

### ISSUE THREAD

**Issue by aadhilrf** [MicrosoftEdge/DevTools#28]
It would be helpful to execute some frequently used JS statements using custom snippets (similar to VS code user snippets) like autocompletion.

**Comment by captainbrosset** [comment]
Hi @aadhilrf, thanks for reaching out and proposing this feature request. I'm not totally clear on what you're asking though. If what you want is a way to write snippets of code in DevTools, and then store them so you can access them again later, then [the Snippets pane](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/snippets) does that already.
Does this help? Or did you have something different in mind?

**Comment by aadhilrf** [comment]
Thanks  @captainbrosset, snippets pane seems to be better than what I had in mind.

**Comment by captainbrosset** [comment]
Awesome, thanks for checking back!
