### ISSUE TITLE
Find & Replace feature broken

### ISSUE THREAD

**Issue by vithom** [MicrosoftEdge/DevTools#280]
Hello,

In the Sources tab of the DevTools, when I would like to find & replace a text, pushing the find & replace button does nothing. It seems this functionality is broken since a few versions.
![image](https://github.com/user-attachments/assets/f3826a96-850f-4f37-8bc7-fcfd55f18b27)

From this page (https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/) the normal behavior should reveal a second bar for the replace term.
![image](https://github.com/user-attachments/assets/f9d0def9-914b-425f-b4ca-1679c07f731d)

Thanks for looking into this issue.
--Vincent THOMAS

AB#54435787

**Comment by leahmsft** [comment]
Thank you for filing this bug. I'll add this on our dev team's backlog.

**Comment by leahmsft** [comment]
Fixed
