### ISSUE TITLE
F12 IEChooser - Network collection agent failed to start

### ISSUE THREAD

**Issue by theohermitte** [MicrosoftEdge/DevTools#282]
Hello !

I am trying to use IEChooser (F12) to track requests for a website in IE mode. This does not work on my computer : I can select the tab, navigate/edit the DOM, but the network tab itself is not working, I get an error "the network collection agent failed to start"
![image](https://github.com/user-attachments/assets/135a3903-7675-4fc5-816b-1067c6918522)

I also have an error that appears in the event viewer with the following message "Échec du démarrage de la session « DiagHubEtwSession.user_paged » avec l’erreur suivante : 0xC000009A". If I translate to english : "failed to start DiagHubEtwSession session with the following error : 0xC000009A"

I tried the following things (according to google searches) :
- Using both 32 bit and 64 bit versions
- Run the tool as both admin and normal user
- Enable the diagnostic hub service
- sfc /scannow
- Probably some other things that I forgot to note

Can anyone help me ?
Thanks !

**Comment by leahmsft** [comment]
Thank you for reaching out. A different team at Microsoft is in charge of IEChooser so please reach out to [Microsoft Support](https://support.microsoft.com/en-us/contactus#!) for help from the right team.
