### ISSUE TITLE
Roblox Game load issue

### ISSUE THREAD

**Issue by Spy22cakes** [MicrosoftEdge/DevTools#283]
2 days ago, ROBLOX worked perfectly fine but the next day It does not load and know each time I click on ROBLOX it loads but then says TypeError: Failed to fetch. This is what the inspect page looks in the console section

Access to fetch at 'https://bareglrrrracier.global.ssl.fastly.net/bear/v1/' from origin 'https://nowgg-bypass.pages.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Access to fetch at 'https://bareglrrrracier.global.ssl.fastly.net/bear/v1/' from origin 'https://nowgg-bypass.pages.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
6A parser-blocking, cross site (i.e. different eTLD+1) script, <URL>, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See <URL> for more details.
loader.js:1  Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at HTMLDocument.<anonymous> (loader.js:1:3025)
roblox.html:1  An iframe on this page was blocked by Microsoft Defender (E5). Its source was https://www.adforgames.com/cd.php?v=1&seq=2&aid=0.2777832379760563&n=6337&size=6
roblox.html:1  An iframe on this page was blocked by Microsoft Defender (E5). Its source was https://www.adforgames.com/cd.php?v=1&seq=1&aid=0.8523718705197132&n=6337&size=3
chromewebdata/:365  Uncaught SyntaxError: Cannot use import statement outside a module
  crbug/1173575, non-JS module files deprecated.
(anonymous) @ chromewebdata/:660
roblox.html:1  An iframe on this page was blocked by Microsoft Defender (E5). Its source was https://www.adforgames.com/cd.php?v=1&seq=3&aid=0.8344138556069076&n=6337&size=6
chromewebdata/:365  Uncaught SyntaxError: Cannot use import statement outside a module
  crbug/1173575, non-JS module files deprecated.
(anonymous) @ chromewebdata/:660
chromewebdata/:365  Uncaught SyntaxError: Cannot use import statement outside a module
(index):660  crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):660
loader.js:1  Uncaught TypeError: Cannot set properties of null (setting 'value')
    at checkEmergencyValues (loader.js:1:1519)
    at loader.js:1:3358
nowgg-bypass.pages.dev/static/embed#https://mathstutor.life/:1  Refused to execute script from 'https://nowgg-bypass.pages.dev/sys/login.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
nowgg-bypass.pages.dev/static/embed#https://mathstutor.life/:1  Refused to apply style from 'https://nowgg-bypass.pages.dev/sys/alert.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
nowgg-bypass.pages.dev/static/embed#https://mathstutor.life/:1  Refused to execute script from 'https://nowgg-bypass.pages.dev/particles.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
nowgg-bypass.pages.dev/static/embed#https://mathstutor.life/:1  Refused to execute script from 'https://nowgg-bypass.pages.dev/app.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Access to fetch at 'https://bareglrrrracier.global.ssl.fastly.net/bear/v1/' from origin 'https://nowgg-bypass.pages.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
loading.js:5  Uncaught TypeError: Cannot read properties of null (reading 'style')
    at loading.js:5:56
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        Don't show again
Access to fetch at 'https://bareglrrrracier.global.ssl.fastly.net/bear/v1/' from origin 'https://nowgg-bypass.pages.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by leahmsft** [comment]
Not a DevTools bug.

**Comment by Spy22cakes** [comment]
Then what kind of issue is it because I can't find what else could be causing this.

**Comment by leahmsft** [comment]
This is an issue with ROBLOX. Please try reaching out to their support team with the error you're seeing.

**Comment by Spy22cakes** [comment]
I'm sorry about that. I only Put it on Github because That what Glacier arcade said to fill out an issue thing. Thanks for telling me where to put the issue. It really helps alot.

________________________________
