### ISSUE TITLE
AI tool, keyboard and arrow away

### ISSUE THREAD

**Issue by Nilsson16** [MicrosoftEdge/DevTools#285]
The 'away' arrow - you can't reach it when having keyboard up. Yes, you can take keyboard down then ezpz but don't we wanna be able to exit through left-pointint-arrow, left side on superior half-

https://github.com/user-attachments/assets/5abd6ae5-15d1-47f4-9137-82d54e8957b0

side of screen despite having keyboard up

**Comment by leahmsft** [comment]
Thank you for filling this, but this isn't related to Edge DevTools. To get your feedback to the right team, go to **Settings and more > Help and feedback** to submit this feedback.
