### ISSUE TITLE
Search for marked text when not possible via document itselr, the prompt, then to able to do ot through the prompt in picture

### ISSUE THREAD

**Issue by Nilsson16** [MicrosoftEdge/DevTools#288]
Hey

As title reads.
![IMG_5674](https://github.com/user-attachments/assets/3f1b6045-83fa-4f7d-88b2-1b0053aeb584)

Normally we can do it like this : see second pic of a SS of this website
![IMG_5676](https://github.com/user-attachments/assets/a6616e4e-b26d-4287-862b-b6c86328871b)

Cheers

**Comment by leahmsft** [comment]
Thanks for filling, but this repo is only for issues related to DevTools. To get your feedback to the right team, please click "Help and feedback" in the menu (shown in your first photo).

Closing since it's unrelated to DevTools
