### ISSUE TITLE
Invisible breakpoint in DevTools's Sources tab

### ISSUE THREAD

**Issue by datvm** [MicrosoftEdge/DevTools#293]
All of a sudden all breakpoints in DevTools are invisible. They still function normally but I cannot see the breakpoint symbol and the line highlight:

https://github.com/user-attachments/assets/7728b156-5369-49d7-82e1-1f95cdd30c04

![image](https://github.com/user-attachments/assets/677daf4e-3619-465a-a4ad-a987e68f08cc)

**Comment by leahmsft** [comment]
Thank you for reporting. This is a known bug, and the engineering team is working on a fix. 

Can you provide details on what browser version you're seeing the bug?

**Comment by datvm** [comment]
@leahmsft it's `Version 131.0.2903.51 (Official build) (64-bit)`

**Comment by leahmsft** [comment]
This should already be fixed in version 131. Are you seeing the issue in both light and dark theme?

**Comment by datvm** [comment]
@leahmsft interesting, if I switch to Dark theme, the problem goes away until I restart Edge.

- Start in Dark: problem never happens.
- Start in Light: happen until I switch to Dark.
  - After that, no matter if I switch back to Light, the problem does not happen again **until I restart Edge in Light theme**

Basically once it enters Dark theme, the problem goes away until restart.

Edit: clarify.

**Comment by Neo-Stark** [comment]
The same issue and the same workaround working here.

**Comment by gryno** [comment]
I get the same bug too, and the workaround described here works as others described. (Interesting that it just started happening today and that others have just found this issue very recently too.)

**Comment by leahmsft** [comment]
Thank you for the repro steps @datvm! I can now see the same bug following your steps. I'll share this back with the engineering team to take a look. I'll update you all once we land a fix.

**Comment by gcolgate** [comment]
Interesting tidbitt, might be clue, n Light mode my window arrangement (console on the bottom, source at the top) does  not work normally, I get no console on the bottom, so there is perhaps some sort of difference in code paths in light mode where it does not load all the settings.

**Comment by leahmsft** [comment]
@gcolgate are you referring to Quick View that missing on Light mode? If you press the Esc key, it should toggle it on and off. Let me know if it still doesn't appear after trying that.

**Comment by wcsison** [comment]
I've got the same issue on131.0.2903.63 (Official build) (64-bit).
When a line number is doubleclicked, the yellow highlight flashes briefly but the red dot doesn't show up. The breakpoint is recorded in the side panel and is active.

**Comment by june07** [comment]
PSA Use [NiM](https://nim.june07.com) for a workaround. 

https://blog.june07.com/flexibility-in-engineering-a-lifesaver-for-javascript-devs-devtools-users/

**Comment by leahmsft** [comment]
The fix is available in Version 133.0.2994.0 (Official build) canary (64-bit) today. It'll also be included in the next Stable release this week. Thanks for your patience, everyone!
