### ISSUE TITLE
"Edit and Resend" feature is not working in 131.0.2903.63

### ISSUE THREAD

**Issue by azmiao** [MicrosoftEdge/DevTools#294]
![企业微信截图_17325023902207](https://github.com/user-attachments/assets/ad91d994-1b1a-4fc5-9b15-0c2f703e7de0)

AB#55231735

**Comment by azmiao** [comment]
After testing, it works on the old version (131.0.2903.51)

**Comment by koljada** [comment]
I'm having exactly the same problem

**Comment by leahmsft** [comment]
Thank you for reporting this bug. I'll add this to the dev team's backlog.

@azmiao @koljada in the meantime, you can use the old version or the canary, dev, beta versions of Edge as a workaround

**Comment by azmiao** [comment]
It seems that it has been fixed in the latest version. (131.0.2903.70)

**Comment by robpaveza** [comment]
This was fixed with a hotfix in .63 and confirmed fixed in .70. Thanks for reporting the issue!
