### ISSUE TITLE
"Edit and Resend" feature is not working in 131.0.2903.63

### ISSUE THREAD

**Issue by dominique-ruest** [MicrosoftEdge/DevTools#295]
Getting the same issue described here: https://github.com/MicrosoftEdge/DevTools/issues/268

Added a collection with a few requests. Worked fine a couple of times. Eventually got 'status 0:  compiler error' when trying to send requests. Then the browser crashed completely and I now get a 404 page when opening any request.

![image](https://github.com/user-attachments/assets/b4f46f0a-b090-4693-b67c-e1c7fc44726a)

**Comment by leahmsft** [comment]
Thank you for reporting this. We are tracking the issue here: https://github.com/MicrosoftEdge/DevTools/issues/294 

Closing this issue since it's a duplicate
