### ISSUE TITLE
Java API wrapper for WebView2 with JDK 18 new Panama FFI ?

### ISSUE THREAD

**Issue by Fxztam** [MicrosoftEdge/DevTools#30]
Hi,

I found WebView2 APIs for Python and GO,
but it would be a great step if there was a WebView2 JAVA API.
The JDK 18 with the Panama project has a header file scanner for FFI API building and
might be possible to build the Java API wrapper for WebView2.
Are there any plans to provide a Java API wrapper for  WebView2?

Thanks, Fried

**Comment by captainbrosset** [comment]
Thanks Fried for reaching out. Unfortunately this repository is about DevTools (the web development tools that are built-in Microsoft Edge), not about WebView2.
Could you please post your question on this repository instead: https://github.com/MicrosoftEdge/WebView2Feedback/issues ?

Thanks for your understanding!
