### ISSUE TITLE
Error when trying to use Co-pilot

### ISSUE THREAD

**Issue by JenniHertrick** [MicrosoftEdge/DevTools#301]
Error shows the following:

We're sorry but we're unable to connect to the service at this time.

![Snag_18abf001](https://github.com/user-attachments/assets/ba7ff98f-76f6-46b7-912a-513d14ce1ac0)

**Comment by leahmsft** [comment]
Thanks for reporting a bug, but this repository is dedicated to issues related to Edge DevTools. To get help and send your feedback to the right place, click on More options (...) > Send feedback in the top right of Copilot.
