### ISSUE TITLE
Breakpoints can not be set

### ISSUE THREAD

**Issue by huulanka** [MicrosoftEdge/DevTools#302]
**Browser Version:**
Edge for Business 131.0.2903.86

**Problem Description:**
When using the developer tools in Edge, I encounter an issue while trying to set breakpoints in the source tab. Although the source code is displayed, attempting to add a breakpoint by clicking on a line does not reflect in the list of breakpoints. Additionally, the red dot, which indicates an active breakpoint, does not appear.

**Impact:**
This issue is urgent as it disrupts our web development process. Our corporate policy mandates the use of this specific version of Edge, and no alternative browsers or versions are permitted.

**Steps to Reproduce:**
1. Open Microsoft Edge for Business (version 131.0.2903.86).
2. Navigate to a webpage and open the Developer Tools .
3. Go to the 'Sources' tab.
4. Attempt to set a breakpoint by clicking on a line of code.

**Expected Behavior:**
The breakpoint should appear in the list of breakpoints, and a red dot should be visible next to the line number.

**Actual Behavior:**
The breakpoint does not appear in the list, and the red dot is absent.

**Additional Information:**
The problem persists even after clearing cache and cookies.
Disabling all extensions did not resolve the issue.
The issue occurs in normal and InPrivate browsing modes.

**I appreciate your prompt attention to this matter, as it significantly impacts our development workflow.**

**Comment by leahmsft** [comment]
Thank you for reporting this. It's a known issue that has already been fixed. Tracked here: https://github.com/MicrosoftEdge/DevTools/issues/293
