### ISSUE TITLE
React Dev Tools not showing tabs in Edge dev tools

### ISSUE THREAD

**Issue by limitedmage** [MicrosoftEdge/DevTools#31]
Steps to reproduce:

1. Install React Dev Tools extension from https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil
2. Open a page that uses React in development mode
3. Open dev tools with F12

Expected:
⚛️  Components and ⚛️ Profiler tabs show in the dev tools

Actual:
Tabs are not visible and there seems to be no way to add them

Screenshot from Chrome:
![image](https://user-images.githubusercontent.com/206864/160496437-958f257c-1301-4bd4-bc58-f112e72354b5.png)

Screenshot from Edge:
![image](https://user-images.githubusercontent.com/206864/160496501-af353c7c-b2ff-4de6-8ef3-c8880a2cac80.png)

**Comment by hxlnt** [comment]
Thanks for the report, @limitedmage. This bug has been fixed in Edge version 100 and later, which is in our Edge insider builds and should be rolling out to all users soon. (You can navigate to `edge://version` to see what version you're using currently.)

In the meantime, a workaround would be to disable the Focus Mode experiment in DevTools settings, then close and reopen DevTools. This should restore the React extension tab on pages with React. Once the browser updates to Edge 100, you can manually reenable the Focus Mode experiment in DevTools and use extensions normally.

Thank you for trying this early build of Focus Mode! We've made a number of great improvements in Edge 100, so I hope you'll continue using it!

**Comment by limitedmage** [comment]
@hxlnt Thank you! Happy to know the fix will be rolling out soon.

**Comment by hxlnt** [comment]
Edge 100 has been released, so closing this issue. Extension support has landed in DevTools for Focus Mode.

**Comment by tonyhallett** [comment]
Not showing when inspecting a WebView2 control.  Should react dev tools be showing ?

![image](https://user-images.githubusercontent.com/11292998/164074143-ef9f9a37-59d4-487d-881f-98c2b179eca3.png)

![image](https://user-images.githubusercontent.com/11292998/164074446-f52934d3-b189-421d-9655-8d75fc7a01eb.png)

**Comment by tonyhallett** [comment]
Took advice from https://github.com/facebook/react/tree/main/packages/react-devtools

> If your app is inside an iframe, a Chrome extension, React Native, or in another unusual environment, try the standalone version instead. Chrome apps are currently not inspectable.

[standalone version](https://github.com/facebook/react/tree/main/packages/react-devtools)

If using create-react-app and you want profiling then `npx react-scripts build --profile`

**Comment by wehnertb** [comment]
I'm in build 105.x and I still do not see these tab in dev tools.  I've tried toggling focus mode on and off, no dice, It's been like this for quite some time.  If I need to use react dev tools, I need to load Chrome and debug from there, because it just doesn't work in Edge any longer.

**Comment by wehnertb** [comment]
I've even installed from Edge's "store" for extensions - same thing.

**Comment by 3dfoster** [comment]
I'm not seeing it in the new focus mode either...

**Comment by heathsias** [comment]
Yup, still missing here as well. When switching between focus mode on and off, they show up upon clicking the 'Restart devtools' button that shows up, but upon closing and reopening dev tools, they are gone.

**Comment by wehnertb** [comment]
I just upgraded to version 107.0.1418.56 and it is showing again.

**Comment by Ashbri4** [comment]
I don't want anything Microsoft

**Comment by antonlabunets** [comment]
Same issue on 109

**Comment by mswiecicki** [comment]
And 111

**Comment by alexewsv** [comment]
It still not works

**Comment by Semmu** [comment]
Same issue here, tabs not showing up in Edge `Version 143.0.3650.139 (Official build) (64-bit)`

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e40bbd09-892d-4f6b-96cb-e3cb0bedaecd" />

**Comment by nithin-pb** [comment]
same issue on version : 

Microsoft Edge | 143.0.3650.139 (Official build) (arm64)

Extension is installed and coming up in the panel, but no option to add tool to the activity bar
