### ISSUE TITLE
Device Emulation Fields Illegible (Low Contrast)

### ISSUE THREAD

**Issue by 1John419** [MicrosoftEdge/DevTools#33]
Developer Tools > Device Emulation

The device name, scaling, and throttling fields are illegible. Contrast levels do not meet WCAG guidelines.

![edge](https://user-images.githubusercontent.com/46386951/161822855-472427b5-6e69-455a-8ef7-796ff0efad68.png)

[AB#38864698](https://microsoft.visualstudio.com/Edge/_workitems/edit/38864698)

**Comment by hxlnt** [comment]
Thanks for reporting this bug, @1John419. That text is certainly hard to read!

I haven't been able to repro this issue in a few different versions of Edge. Could provide your OS, Edge version, and DevTools theme, if set? That might help us better understand what's causing this issue.

Edge 102.0.1216, Windows 11 (dark OS theme), Dark+ (default) DevTools theme:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/9647195/161842845-6abfb649-7638-499f-bd82-7c3474534303.png">

**Comment by 1John419** [comment]
![ss01](https://user-images.githubusercontent.com/46386951/161862799-f9bcb372-f11e-44c5-8829-4637b19e9588.png)
![ss02](https://user-images.githubusercontent.com/46386951/161862815-96dcefd3-3b5b-40c4-a323-e4c6145072ba.png)
![ss03](https://user-images.githubusercontent.com/46386951/161862827-d779a3bf-47ed-4822-9f14-fdb676bb8da2.png)

**Comment by 1John419** [comment]
I now observe that where DevTools is docked effects the results.  Previous screen capture is undocked. Docked left, bottom, and right, it looks like these:

![left](https://user-images.githubusercontent.com/46386951/161864473-ad3796fe-c9cb-4407-a911-63207eabd217.png)

Even here, the screen height field is very poor constrast...

**Comment by captainbrosset** [comment]
Thanks for the extra details you provided, they do help.
I tested with Edge 100 (beta right now) with the default dark+ theme, on Windows 11, and was able to reproduce:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1152698/161919706-7592f78a-e035-404f-9dd6-38561bfe0b7f.png">

I can also confirm that this only happens when DevTools is undocked.

I tested with 101 and 102, and the issue seems fixed in those versions.

I'll create a task on our backlog to investigate more and hopefully provide a solution.

**Comment by captainbrosset** [comment]
I tested again in the latest Canary version of Edge today, and the issue appears to be fixed there. Whether DevTools is docked or undocked, the throttling, zoom level, and device drop-downs all have good color contrast ratio.
So I'll mark this issue as fixed.

You also reported another contrast issue with the device height. I'll open another issue just for this.
