### ISSUE TITLE
Toggle vertical orientation for console drawer

### ISSUE THREAD

**Issue by noobtiger** [MicrosoftEdge/DevTools#34]
Currently DevTools allows users to view different panels via console drawer, this is quite useful if users want to quickly check console messages when viewing Elements or any other panel.
![image](https://user-images.githubusercontent.com/11323000/161850122-52b82027-bb46-4029-bfd1-6e6474d183cd.png)

This is sufficient for panels that are not heavy, but while viewing more information-dense panels such as Elements, Sources, 3D view etc. simultaneously in horizontal drawer, it is not optimal experience.
I believe adding a toggle button to set drawer to vertical orientation will alleviate this issue, and it is easy to revert back to default orientation. 

Demo video

https://user-images.githubusercontent.com/11323000/161852588-50016ac7-c1be-4504-ae95-ff59aa2f1bd8.mp4

AB#38958191

**Comment by captainbrosset** [comment]
I love this proposal, and even more the fact that you've already built a prototype 😍

Seems like a great proposal to evaluate for sure, as I know users of DevTools have been asking for more customization abilities for years.

A few relevant asks:
* https://webwewant.fyi/wants/5f60115e2058780fd87faa72/
* https://bugzilla.mozilla.org/show_bug.cgi?id=1121414
* https://discourse.mozilla.org/t/undock-devtools-panes-and-place-them-side-by-side/33711

I'm sure there are others too.

**Comment by captainbrosset** [comment]
We'll track this in our internal backlog in order to more easily consider and prioritize this.

**Comment by hxlnt** [comment]
This feature has shipped and landed in Edge 105 (Canary)! 🎉

https://twitter.com/partytimeHXLNT/status/1546623683636199424
