### ISSUE TITLE
Ability to do full, deterministic GC

### ISSUE THREAD

**Issue by stjanovi** [MicrosoftEdge/DevTools#40]
Forcing a garbage collection, such as with the button in dev tools, doesn't collect all the memory it can. It seems like there are still some heuristics that apply. This behavior is not clear to newcomers.  Ultimately this behavior makes it harder to find memory leaks.

**Comment by captainbrosset** [comment]
Thanks for reaching out @stjanovi. Are you able to elaborate a bit more on this? How do you know that not all collectable memory is not collected?

@joselea do you know what happens exactly when pressing the GC button? I was under the impression that it would collect everything, but apparently not.

**Comment by stjanovi** [comment]
I have a scenario in my application where an object was not collected until about the 20th repeat of the scenario per an Allocation Timeline. Using the GC button did not collect the memory. If I comment out certain properties of the object, it is collected earlier, after just one iteration.

Others encounter nondeterminism as well. See [this tool](https://github.com/samccone/drool/blob/b17a0a54025272d202282aff00bb1b67f5519114/lib/index.js#L32) that keeps doing GCs until the count stops changing.

**Comment by sethbrenith** [comment]
What does 10 to 20 repetitions of the scenario mean? Does this test run JavaScript continuously, or is the main thread sometimes idle while waiting for the next event? The trash can icon in the devtools does not collect garbage immediately, but instead queues a task to collect garbage when there is nothing else running on the main thread. (Somewhat ironically, the point of this delay is to [make the behavior *more* deterministic](https://chromium-review.googlesource.com/c/v8/v8/+/2307217).) Can you provide a heap snapshot that shows an object which should have been collected but wasn't?

**Comment by stjanovi** [comment]
I don't have a snapshot I can share publicly. The scenario is manually navigating between pages of my application by clicking buttons in the application. A repetition is clicking a button to navigate from Page A to Page B, and then clicking a button to navigate back to Page A. My app can track "important" work done during a page load, so in my testing I wait for those tracked tasks to finish to know when the page is considered finished doing work as part of load, click the trash can icon a couple of times and wait a few seconds, and then stop recording the Allocation Timeline. It's possible I'm not waiting long enough if I only wait a few seconds. If we assume the trash can icon _does do_ deterministic garbage collection if someone waits long enough after clicking it, it would be good to show in the devtools UI when the cleanup finishes as well as make window.gc or something return a Promise so automation can know when GC has finished.

**Comment by captainbrosset** [comment]
@sethbrenith any idea whether exposing events via the CDP protocol for DevTools (and automation tools) to know when garbage collection is done running? Or does the `HeapProfiler.collectGarbage` already only returns once GC is done?

**Comment by sethbrenith** [comment]
I like the idea of a CDP message indicating when the GC has finished, but I doubt it would help in this case. If the page was idle enough to listen for button clicks, then the GC will happen right away. If an object is still hanging around after clicking the trash can multiple times, there's probably a bug somewhere, but I can't say more without a heap snapshot or repro steps.

> make window.gc or something return a Promise

I just learned a few days ago that window.gc already can return a Promise, if you request asynchronous execution like so: `gc({execution:'async'})`. Otherwise, it runs synchronously: by the time gc() returns, the garbage collection is done.

**Comment by stjanovi** [comment]
@sethbrenith based upon what you've shared so far,  it sounds like there may just be bugs in particular scenarios and they would have to be fixed on a case by case basis when people share snapshots with you. As such, I'll close this for now.
