### ISSUE TITLE
The issues panel includes browser extensions

### ISSUE THREAD

**Issue by besenwagen** [MicrosoftEdge/DevTools#41]
Although "Include third-party issues" is not ticked, I get the issue

> Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

with each of the following extensions:

- Bitwarden
- axe DevTools
- Redux DevTools

That seems counterproductive for everything but extension debugging.

Version 100.0.1185.27 (Official build) beta (64-bit) on Ubuntu 20.04.4 LTS.

I'm pretty sure I had the same issue on macOS, but that was in 2021, so mild anecdata disclaimer there.

**Comment by captainbrosset** [comment]
Hey @besenwagen, thanks for reporting this. It would be super helpful if you could provide a URL to a site where we can test this. I'm wondering if this always happens, or just with some specific URLs.

Also, just to double check my understanding, are these the right steps to reproduce the issue:

1. Install one of the extensions you mentioned
2. Open the Issues panel in DevTools
3. Clear the **Include third-party issues** checkbox
4. Reload the page to re-initialize the list of issues

What you're saying is if I have any of the extensions, then the unrelated navigator issue comes up, and if I don't, then it doesn't, right?

**Comment by antross** [comment]
@captainbrosset my guess is these extensions are injecting scripts into the page that are getting picked up by the Issues panel. This particular issue about the UA string comes from upstream Chromium so discussions about filtering out reports for extension-injected scripts may need to start there if that's what's happening.

**Comment by antross** [comment]
@captainbrosset I think extension-generated issues shouldn't be reported at all (or at least have some separate opt-in). The main focus of the Issues panel is supposed to be on issues with the current page and the "3rd party" classification is for external content used by the current page (e.g. from a CDN).

That said, I'm not sure we have a good way to distinguish between extension-generated scripts and those that are part of the page, but we can sort out implementation discussions on the Chromium bug. The main point is we'd rather not report these as they just create noise for most developers trying to resolve issues in their own content.

**Comment by besenwagen** [comment]
@captainbrosset To open a chromium issue I have to tick a checkbox to confirm that I searched for existing issues using an interface that is so abhorently terrible that I simply cannot. Sorry.

I don't know why accessibility and open source have to be mutually exclusive.

**Comment by captainbrosset** [comment]
Understood. I will open a chromium issue to report this problem. Thanks for reporting!
Here is the upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1317536
Let's close this github issue now.
