### ISSUE TITLE
Allow friendly names to be added to heap snapshots

### ISSUE THREAD

**Issue by jarmit** [MicrosoftEdge/DevTools#43]
Currently today, all of Objects, Arrays, etc. are all combined within the same constructor within a heap snapshot view. This makes it difficult to get a summary of what types of objects are causing the most memory problem. If instead, we could provide a friendly name to objects, so the aggregation of those events could be based off of friendly name, this would help us in allowing to target the correct objects that will get us the most bang for our buck.

AB#39492569

**Comment by captainbrosset** [comment]
This seems like an interesting idea that would, for sure, make it easier to use the snapshot view. I think @zoherghadyali would want to hear about this.

**Comment by leahmsft** [comment]
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2024/10/devtools-130#improved-names-of-javascript-objects-in-heap-snapshots
