### ISSUE TITLE
Turn off remote debugging to open this site in IE mode otherwise it might not work as expected.

### ISSUE THREAD

**Issue by Keras08** [MicrosoftEdge/DevTools#46]
**What happened?**
When using autoit WebDriver UDFs with MSEdge driver and IE mode the MSEdge browser starts and visits the correct page but doesn't enable IE mode and displays "Turn off remote debugging to open this site in IE mode otherwise it might not work as expected."

**How can we reproduce the issue?**
```
#include "include\JSON.au3"
#include "include\WinHttp.au3"
#include "include\wd_core.au3"
#include "include\wd_helper.au3"

WD_Option('Driver', @ScriptDir & '\include\' & ([@Compiled](https://www.autoitscript.com/autoit3/docs/macros.htm#%40Compiled) ? '' : 'Exe_externe\') & 'msedgedriver.exe')
_WD_Option('DriverParams', '--log trace ')
_WD_Option('Port', 9515)
$sDesiredCapabilities = '{"capabilities": {"alwaysMatch": {"ms:edgeOptions": {"args": ["--ie-mode-force"]}}}}'
_WD_Startup()
$sWDSession = _WD_CreateSession($sDesiredCapabilities)
_WD_Navigate($sWDSession, "https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-faq#does-ie-mode-on-microsoft-edge-support-the--nomerge--option-that-was-supported-in-internet-explorer-11-")
```

**Operating System**
Windows 10

**Autoit version**
3.3.16.0

**What are the browser driver(s) and version(s) where you see this issue?**
Microsoft Edge WebDriver 100.0.1185.50

**Comment by bwalderman** [comment]
msedgedriver.exe does not support Edge in IE Mode. To drive IE Mode, you will need to use IEDriver. See https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode for instructions on getting started.
