### ISSUE TITLE
image

### ISSUE THREAD

**Issue by Hein-MinThant** [MicrosoftEdge/DevTools#57]
<!Doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="description" conent="This is an awesome website">
</head>
<title>
identity
</title>
<body>
<image src=blob:https://account.microsoft.com/5459f31e-d1ac-40ed-93ce-50513571db83></image>
            {image width; 100px:
                         border-radius; 50px:
                          float; left:
                          mirgrin-right; 100px:}
</body>
</html>

**Comment by captainbrosset** [comment]
Hm, this isn't an issue that we can act on. I'll close it now. If you have a bug or a feature request that you would like to share with us, please file a new issue with as much detail as possible.
