### ISSUE TITLE
SECURITY ADDVISOR

### ISSUE THREAD

**Issue by Sam6131966** [MicrosoftEdge/DevTools#70]
WHERE WOULD I TAKE UP THIS ISSUE I HAVE 10,000+REWARDS AND IT SAYS I WANT TO GIVE IT TO CHARITY I DID NOT PICK THIS OPT OIN IM STARING AND NEED THAT MONEY WHO PICK THIS I DIDNT WHERE DO I TAKE THIS ISSUE

**Comment by codepo8** [comment]
Spam Spam Spam, wonderful spam

**Comment by Sam6131966** [comment]
sorry new  at  that

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
