### ISSUE TITLE
opera sidebar and multiple workspace

### ISSUE THREAD

**Issue by AkramiPro** [MicrosoftEdge/DevTools#72]
please add multiple workspace and left sidebar like opera . this is very useful for me . please add support for it . thank you

![image](https://user-images.githubusercontent.com/54323929/174638855-f59f906b-ca2f-4311-b3d5-5ffbc164003a.png)

**Comment by captainbrosset** [comment]
This repository is specific to DevTools, and I think your feature request is for the browser instead. Or did I get this wrong?
