### ISSUE TITLE
Extensions reinstall every 15-30 minutes, signed out and then hidden from Edge toolbar

### ISSUE THREAD

**Issue by mbell85** [MicrosoftEdge/DevTools#76]
Hello!

My name is Mark Bell and I'm an admin at a medium-sized business in Murfreesboro, TN. I'm not sure if I'm in the right place or not here, so forgive me if this is off-topic. 

After installing 103.0.1264.37 we are noticing a problematic behavior on all domain-joined endpoints (confirmed by reverting back to 102 builds where the issue does not exist). 

We currently have GPO set to allow a handful of extensions in Edge and we block all others. Every time GPO refreshes on this build, all extensions appear to be re-installing, get hidden in the Edge toolbar and get signed out of (for those extensions that require sign-in, such as the My-Apps Secure Sign In extension). 

I am open to someone from the Edge team collecting relevant logs, etc. I can't find any information for reaching out to their team directly. 

Thanks, 

Mark

**Comment by captainbrosset** [comment]
Thank you for reaching out. This repository isn't exactly the right place for this feedback as this repo is focused on the Edge Developer Tools. I'll find out what is the best place for your feedback and get back to you.

**Comment by captainbrosset** [comment]
@mbell85 I think the best place for you to send this feedback is by using the Feedback mechanism that is built into the browser itself.
To access it: Click **Settings and more** (the `...` button) > **Help and feedback** > **Send feedback**.

This will reach the browser team and then makes its way from there to the right folks who can help you.
