### ISSUE TITLE
Hovering element on devtools does not reveal it on the page while using 'minimal mode' as overlay scrollbar

### ISSUE THREAD

**Issue by tusharsnn** [MicrosoftEdge/DevTools#94]
In devtools, Hovering over html elements on the Elements tab used to reveal/highlight them on the webpage but from the previous version, it is no longer working as expected. I have found from other online forums that this issue is not specific to Edge and another chromium browser eg. chrome also has this problem. So it might be more of a chromium issue than Edge, but I am creating it here as I could not find any place to file an issue there.

The highlighting seems to work only in certain situations when the Elements tab is:
1) zoom out enough that all the page's markup is visible without scrolling (hence scroll bars should not be visible).
2) zoom in enough that starts working again.

#### Video demo for the issue

https://user-images.githubusercontent.com/55626797/186585385-dd6b72d8-e7f3-4a3a-ba12-fd1f4b4d28a8.mp4

#### Edge Version: 
104.0.1293.63 (Official build) (64-bit)

AB#41198302

**Comment by captainbrosset** [comment]
I just tested some more, and I was only able to reproduce this issue in the current Edge stable version (104). 

Testing on Edge Beta (105) and Canary (106) showed that the bug was fixed there.
I also tested on Chrome Stable and Canary, and they both worked fine for me.

So, my assumption is that the bug has already been fixed in chromium and deployed in all versions of Chrome. As for Edge, it should be a matter of days, since it already appears to be in Beta.

The next Edge Stable version should be available to users starting on September 1st. Let's test again then and see if the issue persists.

**Comment by tusharsnn** [comment]
It would be great if you can send the chromium bug tracker issue link here as well.

**Comment by tusharsnn** [comment]
I think it is safe to close this for now and lets wait for the next stable release.

**Comment by tusharsnn** [comment]
I am afraid that the issue is not related to chromium but to an experimental feature available on MS Edge that makes the scrollbar fade away into minimal mode. 

Edge Feature Flag: edge://flags/#edge-overlay-scrollbars-win-style

Enabling the feature works fine but **'Enabled minimal mode'** option is causing the problem.

**Comment by captainbrosset** [comment]
Thanks for testing again and reporting your findings. I will make sure this shows up on our team's radar for prioritization and investigation.

**Comment by tusharsnn** [comment]
With this [commit](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4110908) inbound, the overlay scrollbar won't break devtools on chromium (and Edge). 
It also changes the behaviour of how hovering works in devtools. As mentioned in the [comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1376377#c13), hovering over the indented space (before the element) will now highlight the parent element instead of the element on that row.
