### ISSUE TITLE
I keep getting prompted to remind me to install npm and nodejs

### ISSUE THREAD

**Issue by BobFrankston** [MicrosoftEdge/DevTools#95]
Of course, I have them installed, but there is no obvious way to get rid of this annoying prompt

![image](https://user-images.githubusercontent.com/5490484/186742645-23f2cff7-24cd-46aa-86de-62de86ebb464.png)

**Comment by hxlnt** [comment]
Thank you for the bug report. The repo for this VS Code extension can be found at https://github.com/microsoft/vscode-edge-devtools. I've linked this issue to a similar open bug there. Hopefully this will help get resolution to your issue more quickly.

**Comment by leahmsft** [comment]
Fixed https://github.com/microsoft/vscode-edge-devtools/issues/2390
